### ISSUE TITLE
chat interface

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#102]
- Does this allow followup questions which takes the context and history of the former questions into account? Thanks! [tweet context](https://twitter.com/svenni_uwe/status/1674414221516476416)

**Comment by cachho** [comment]
Interesting, cause that's basically the question I asked in #113. Embedchain should definitely be able to handle history, but if it's supposed to keep a self-contained history, we have to worry about sessions and invalidation, so I think it should be part of the frontend.

**Comment by taranjeet** [comment]
Working on this. Raising a WIP PR.

**Comment by taranjeet** [comment]
Released in v.0.0.15. Closing this.
