### ISSUE TITLE
httpx.ConnectError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by xxm1668** [embedchain/embedchain#1026]
### 🐛 Describe the bug

httpx.ConnectError: [Errno 101] Network is unreachable

**Comment by xxm1668** [comment]
![截图 2023-12-19 09-43-32](https://github.com/embedchain/embedchain/assets/129041904/b04adb9a-038e-4e17-8014-d696a5162f17)

**Comment by deshraj** [comment]
Thanks for opening the issue @xxm1668   

Can you please post the full error traceback so that we can help you better?

**Comment by xxm1668** [comment]
vpn开着就可以了，但是不支持Vllm服务

**Comment by Dev-Khant** [comment]
Closing the issue as the problem is not clear. Please feel free to open it again if needed.
