### ISSUE TITLE
Response Amount - Custom OpenAI Settings

### ISSUE THREAD

**Issue by Meathelix1** [embedchain/embedchain#103]
Hello,

Is there a setting to increase the amount for the response? 

I am currently getting a very limited response. 

Would also love custom settings for OpenAI.

**Comment by cachho** [comment]
You mean something like #63 ? Taking more documents into account? Or more characters?

**Comment by cachho** [comment]
closing this because the issue has not been described in a way where we can work with it. Please reopen in case you can reproduce and describe the issue in the latest version.
