### ISSUE TITLE
just plain doesn't understand Even with dozens of q&a pairs

### ISSUE THREAD

**Issue by kingmaiker** [embedchain/embedchain#106]
This simply does not understand a thing that I give it, it doesn't reference any data, it doesn't reference any of the QAs. It just tells me it doesn't know what I'm talking about but maybe I ought to go to the website of the restaurant if I want to look at the menu.

like am I stupid or what

**Comment by taranjeet** [comment]
Hey @kingmaiker , so sorry for this bad experience. You may be indexing a data format for which chunking and retrieval strategies needs improvement.

If you can share more details about this, will figure it out.

Also happy to get on a call and dive more into it with you.

**Comment by kingmaiker** [comment]
I'm so glad you responded, I actually managed to get it to work. I think I
was utilizing the query incorrectly. And I didn't realize, don't ask me why
I was this dumb, how important The actual system prompt is when trying to
pull the information. I had a different idea in mind, which I should
probably just skip over from now on and go right to RTFM. "reading the
***ing manual"

**Comment by cachho** [comment]
Glad that it worked out in the end.
