### ISSUE TITLE
ImportError: cannot import name 'ALLOWED_NETLOCK' from 'langchain.document_loaders.youtube'

### ISSUE THREAD

**Issue by FrankTseng168** [embedchain/embedchain#1064]
### 🐛 Describe the bug

config_huggingface = {
  'llm': {
    'provider': 'huggingface',
    'config': {
      'model': 'google/flan-t5-xxl',
      'temperature': 0.7,
      'max_tokens': 1000,
      'top_p': 0.8,
      'stream': False
    }
  },
  'embedder': {
    'provider': 'huggingface',
    'config': {
      'model': 'sentence-transformers/all-mpnet-base-v2'
    }
  }
} 

import os
from embedchain import Pipeline as App
os.environ["HUGGINGFACE_ACCESS_TOKEN"] = ""

# Create a bot instance
elon_bot = App.from_config(config=config_huggingface)

# Embed online resources
elon_bot.add("https://en.wikipedia.org/wiki/Elon_Musk")
elon_bot.add("https://www.forbes.com/profile/elon-musk")

# Query the bot
elon_bot.query("How many companies does Elon Musk run and name those?")

# Chat the bot
elon_bot.chat("How many companies does Elon Musk run and name those?")

**Comment by LouisMonierSpark** [comment]
Same here. I face this error with the code for the [quickstart paid model](https://docs.embedchain.ai/get-started/quickstart#paid-models):
`--> 140     from langchain.document_loaders.youtube import \
    141         ALLOWED_NETLOCK as YOUTUBE_ALLOWED_NETLOCS
    143     if url.netloc in YOUTUBE_ALLOWED_NETLOCS:
    144         logging.debug(f"Source of `{formatted_source}` detected as `youtube_video`.")

ImportError: cannot import name 'ALLOWED_NETLOCK' from 'langchain.document_loaders.youtube' (/Users/louisspark/miniconda3/envs/spark/lib/python3.8/site-packages/langchain/document_loaders/youtube.py)`

**Comment by deven298** [comment]
@FrankTseng168 @LouisMonierSpark this should be fixed in the next release! Please feel free to reach out if there is any other problem.
