### ISSUE TITLE
Add txt file as the new data loader

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#1069]
### 🚀 The feature

There should be a data loader to read txt files

### Motivation, pitch

Support wider category of data

**Comment by eren-darici** [comment]
Hey! I think somebody already added.

**Comment by Dev-Khant** [comment]
It's already added https://github.com/embedchain/embedchain/blob/main/embedchain/loaders/text_file.py.
Documentation is remaining.

**Comment by Dev-Khant** [comment]
Fixed here #1410
