### ISSUE TITLE
Excel File Support

### ISSUE THREAD

**Issue by AbrahimZaman360** [embedchain/embedchain#1103]
### 🚀 The feature

I need excel file support!

### Motivation, pitch

ALot

**Comment by AbrahimZaman360** [comment]
X

**Comment by Dev-Khant** [comment]
@deshraj Do we need this, can I work on it?

**Comment by deshraj** [comment]
Yes @Dev-Khant, we definitely need this. Yes, please go ahead.

**Comment by Dev-Khant** [comment]
@deshraj I raised a PR, please review it. Thanks :)
