### ISSUE TITLE
Failed to install frontend requirements.

### ISSUE THREAD

**Issue by jmanhype** [embedchain/embedchain#1120]
### 🐛 Describe the bug

❌ Failed to install frontend requirements. Error: [WinError 2] The system cannot find the file specified
using the new commands im getting an error
its not working

**Comment by deshraj** [comment]
@jmanhype thanks for reporting the error. Can you please paste the full error log here?

**Comment by alpapaydin** [comment]
It's a problem with python popen failing to start yarn at given dir. More info below:
https://stackoverflow.com/questions/36324/the-system-cannot-find-the-file-specified-when-invoking-subprocess-popen-in-py

Workaround solution would be to go to created ui folder then "yarn" to install and "yarn dev" to start server.

**Comment by deshraj** [comment]
Thanks for suggesting the answer @alpapaydin. 

@jmanhype we also released the dockerized version of this so now you can setup the full stack RAG app using docker. Just have to run the following commands:

```bash
ec create-app my-app --docker
cd my-app
ec start --docker
```

Full docs here: https://docs.embedchain.ai/get-started/full-stack

**Comment by jmanhype** [comment]
I like your slack ai . lets do one for discord id pay top dollar
