### ISSUE TITLE
ImportError: cannot import name 'OpenSourceApp' from 'embedchain'

### ISSUE THREAD

**Issue by tunahorse** [embedchain/embedchain#1121]
### 🐛 Describe the bug

Hello, I got this issue while running the latest version. 

`ImportError: cannot import name 'OpenSourceApp' from 'embedchain' (/usr/local/lib/python3.11/site-packages/embedchain/__init__.py)`

Confirmed I am using the latest package 0.1.54

**Comment by deshraj** [comment]
Hey @tunahorse, can you please share the code? Looks like you are using really old syntax and `OpenSourceApp` class has been removed long time ago from the package. 

If you want to create an open source app, you can follow the instructions here: https://docs.embedchain.ai/get-started/quickstart#open-source-models

**Comment by rodpenna** [comment]
I'm getting the same error but with App.
ImportError: cannot import name 'App' from 'embedchain' (c:\Users\Rodrigo\AppData\Local\Programs\Python\Python312\Lib\site-packages\embedchain\__init__.py)

Using version 0.1.72

**Comment by deshraj** [comment]
Closing this issue since this is no longer relevant to the latest version of embedchain package. @tunahorse please feel free to reopen the issue if the issue persists with the latest version of Embedchain package. Thanks!
