### ISSUE TITLE
Replace deprecated type aliases from typing module

### ISSUE THREAD

**Issue by sandrasgg** [embedchain/embedchain#1128]
As detailed in [PEP 585](https://peps.python.org/pep-0585/#implementation), some type aliases are to be deprecated as of Python 3.9, so they should be replaced by the ones indicated in the previous link.

I'm happy to do it myself, if admins could please assign, thanks!

**Comment by deshraj** [comment]
Thanks for creating the issue. Please feel free to work on this.
