### ISSUE TITLE
Add support for Hugging Face Inference Endpoint as LLM

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#1133]
### 🚀 The feature

Requested by Rami on Embedchain slack. Link: https://embedchain.slack.com/archives/C05RG7CJKC6/p1704630024321719

<img width="869" alt="Screenshot 2024-01-07 at 9 43 29 PM" src="https://github.com/embedchain/embedchain/assets/2945708/b6d76ac0-488a-44e5-afe1-adc51512353b">

### Motivation, pitch

Motivation is to provide support for different LLM providers possible.

**Comment by mae5357** [comment]
Hey @deshraj! I would be interested in this. Would you want a new llm class, or to modify HuggingFaceLlm()?

**Comment by deshraj** [comment]
Thanks a lot for offering help. ❤️

Yeah we want to add support in the existing class where the user can pass the inference endpoint and other params (optional). 

Let me know if you have any other questions.
