### ISSUE TITLE
Add support for json mode for OpenAI LLMs

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#1156]
### 🚀 The feature

Requested by a user on slack: 

<img width="497" alt="Screenshot 2024-01-11 at 12 58 28 AM" src="https://github.com/embedchain/embedchain/assets/2945708/b0d9f92d-d7de-496e-8925-d7cb1d77574e">

https://embedchain.slack.com/archives/C05RG7CJKC6/p1704906334878579

Docs: https://community.openai.com/t/how-do-i-use-the-new-json-mode/475890

### Motivation, pitch

Provide support for all features offered by OpenAI llms.

**Comment by Praj-17** [comment]
Hi is this implemented, yet? I would want to implement it if it is not done.

**Comment by hardik1408** [comment]
@deshraj can I try implementing this issue?
