### ISSUE TITLE
how  to use local model, already download from huggingface, 

### ISSUE THREAD

**Issue by sporterman** [embedchain/embedchain#1214]
### 🐛 Describe the bug

such as  LLM  chatglm, embedding models bge

**Comment by ssgupta905** [comment]
please refer- https://discuss.huggingface.co/t/run-models-on-a-desktop-computer/31125

**Comment by sporterman** [comment]
@ssgupta905 this cannot solve ,  my question is to use LLM in embedchain project,  not just use a LLM to  inference,   
`import os
# replace this with your HF key
os.environ["HUGGINGFACE_ACCESS_TOKEN"] = "hf_xxxx"

from embedchain import App
app = App.from_config("mistral.yaml")
app.add("https://www.forbes.com/profile/elon-musk")
app.add("https://en.wikipedia.org/wiki/Elon_Musk")
app.query("What is the net worth of Elon Musk today?")
# Answer: The net worth of Elon Musk today is $258.7 billion.
`

`llm:
  provider: huggingface
  config:
    model: 'mistralai/Mistral-7B-Instruct-v0.2'
    top_p: 0.5
embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'
`

how to use LLM model already download at my pc  in above code ?

**Comment by hushi19910329** [comment]
I've encountered the same issue. I deployed my fine-tuned llama2 model using Xinference, but I haven't found a way to integrate it into Embedchain. Is there a solution for this?

**Comment by deshraj** [comment]
Hey @hushi19910329, we recently added support for running local models from HF. Please see the docs here on how to use it: https://docs.embedchain.ai/components/llms#hugging-face-local-pipelines

**Comment by blake41** [comment]
In the example you cite "model": "Trendyol/Trendyol-LLM-7b-chat-v0.1",
What file needs to be downloaded from HF, and is this value supposed to be a pointer to where the file is? or is the file supposed to be in the root directory and use this naming convention?

**Comment by kaust2018** [comment]
It only works for llm, does not work for embedder
