### ISSUE TITLE
Ollama integration not working

### ISSUE THREAD

**Issue by rapidarchitect** [embedchain/embedchain#1220]
### 🐛 Describe the bug

tried using the ollama example and i get openai.AuthenticationError: Error code: 401

here is the code.
import os
from embedchain import App

# load llm configuration from config.yaml file
app = App.from_config(config_path="config.yaml")
app.query("What is the capital of France?")

**Comment by rapidarchitect** [comment]
the config.yaml is here, and yep ollama is running and i have pulled llama2

llm:
  provider: ollama
  config:
    model: 'llama2'
    temperature: 0.5
    top_p: 1
    stream: true

**Comment by KeithHanson** [comment]
Hm. +1 for me as well. This example still hits OpenAI:


## test.py
```
from embedchain import App
app = App.from_config(config_path="ollama_embedchain.yaml")
print(app)

app.add('./docs/global_politics.pdf', data_type='pdf_file')

print(app.query("What century did we begin to see an extended definition of the political community?"))
```

## ollama_embedchain.yaml
```
llm:
  provider: ollama
  config:
    model: 'llama2'
    temperature: 0.5
    top_p: 1
    stream: true
 ```
 
 I noticed, though, that the embed options for embedchain do not include ollama? Maybe this error is happening because it defaults to openai?

**Comment by KeithHanson** [comment]
I've taken my first stab here - will submit a proper pull request soon:

https://github.com/KeithHanson/embedchain/tree/ollama-embedding-provider

**Comment by rapidarchitect** [comment]
I got it working with streamlit in this code.
make sure you install sentence-transformers and delete your original .embedchain folder

`import databutton as db
import streamlit as st
import os

st.subheader(" Create Instant ChatBot 🤖 using `embedchain`")
st.markdown(" Repo : [Embdedchain](https://github.com/embedchain/embedchain)")


import time
import openai
from embedchain import App

@st.cache_resource
def botadd(URL):
    databutton_bot = App.from_config(config={
    "llm": {
        "provider": "ollama",
        "config": {
            "model": "llama2",
            "temperature": 0.5,
            "top_p": 1,
            "stream": True
        }
    },
    "embedder": {
        "provider": "huggingface",
        "config": {
            "model": "BAAI/bge-small-en-v1.5"
        }
    }
})
    # Embed Online Resources
    databutton_bot.add("web_page", URL)
    return databutton_bot

# st.subheader(" Create Instant ChatBot 🤖 using `embedchain`")
# st.markdown(" Repo : [Embdedchain](https://github.com/embedchain/embedchain)")

if "btn_state" not in st.session_state:
    st.session_state.btn_state = False

prompt = st.text_input(
    "Enter a URL: ",
    placeholder="https://docs.databutton.com/howto/store-and-load-faiss-vectordb",
)
btn = st.button("Initialize Bot")

if btn or st.session_state.btn_state:
    st.session_state.btn_state = True
    databutton_bot = botadd(prompt)
    st.success("Bot Ready ☑️! ")

    # Initialize chat history
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # Display chat messages from history on app rerun
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Accept user input
    if prompt := st.chat_input("What is up?"):
        # Add user message to chat history
        st.session_state.messages.append({"role": "user", "content": prompt})
        # Display user message in chat message container
        with st.chat_message("user"):
            st.markdown(prompt)
        # Display assistant response in chat message container
        with st.chat_message("assistant"):
            message_placeholder = st.empty()
            full_response = ""
            assistant_response = databutton_bot.query(prompt)

        # Simulate stream of response with milliseconds delay
        for chunk in assistant_response.split():
            full_response += chunk + " "
            time.sleep(0.05)
            # Add a blinking cursor to simulate typing
            message_placeholder.markdown(full_response + "▌")
        message_placeholder.markdown(full_response)
        # Add assistant response to chat history
        st.session_state.messages.append(
            {"role": "assistant", "content": full_response}
        )
else:
    st.info("Initiate a bot first!")`

**Comment by KeithHanson** [comment]
> "embedder": {
> "provider": "huggingface",
> "config": {
> "model": "BAAI/bge-small-en-v1.5"
> }
> }

That is the huggingface provider, not embedding via ollama, just fyi. This will indeed get it working, though it skips ollama for embedding and uses HF, even though Ollama _DOES_ have embedding support.

**Comment by rapidarchitect** [comment]
Good point, i figured let me try just llm first then embedding second :)

**Comment by golemus** [comment]
I lost like 2 hrs

pls add to docs on ollama:

os.environ["OLLAMA_HOST"] = "http://127.0.0.1:11434"

and in config.yaml

something like

embedder:
  provider: ollama
  config:
    model: znbang/bge:small-en-v1.5-q8_0
    base_url: http://127.0.0.1:11434
    
 otherwise it will keep looking for   embedder on openai

**Comment by GZack2000** [comment]
Agree with @golemus here. 

The docs should mention that the embedder needs to be set in config.

For those using Ollama itself as embedding provider, ensure to add that to config so that it doesn't hit OpenAI for embeddings
```python
 config = {
        "llm": {
        "provider": "ollama",
        "config": {
            "model": "llama3.1:latest",
            "temperature": 0,
            "max_tokens": 8000,
        },
    },
    "embedder": {
        "provider": "ollama",
        "config": {
            "model": "nomic-embed-text:latest",
        },
    },
 }
```

**Comment by swaipdev** [comment]
Hi guys, as far as you know is there any way, for an offline desktop app, to NOT use Ollama for local embeddings? 

I posted here what I'm trying to achieve https://github.com/mem0ai/mem0/discussions/2015

Thanks in advance
