### ISSUE TITLE
[Youtube Loader] Add support for storing timestamp metadata when loading youtube videos

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#1244]
### 🚀 The feature

Currently, we don't store the timestamp of youtube videos which is something important for youtube videos which are annotated by the creators to get relevant context. We want to store all relevant information as part of the metadata so that we can later refer to it during the retrieval. 

![Screenshot 2024-02-06 at 11 40 29 AM](https://github.com/embedchain/embedchain/assets/2945708/bfe316d0-8dd1-4b50-bdea-3c9ac64c1122)

### Motivation, pitch

Requested by a user on discord community: https://discord.com/channels/1121119078191480945/1125758905310519327/1204043123781673011

**Comment by hardik1408** [comment]
Hey @deshraj ,
Can I try working on this?

**Comment by Esparon1** [comment]
hi @deshraj , Can I try working on this ?

**Comment by deshraj** [comment]
Sure @Esparon1, feel free to work on it.
