### ISSUE TITLE
Add support for embedding model from Cohere

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#1248]
### 🚀 The feature

Cohere provides embedding model. We need to support that

### Motivation, pitch

A user reported a bug (issue #1247 )
Better support for all the major providers.

**Comment by Dev-Khant** [comment]
@taranjeet  Can I pick this up?

**Comment by Dev-Khant** [comment]
@deshraj Can I start with this?

**Comment by deshraj** [comment]
Yeah sure, please feel free to work on it.
