### ISSUE TITLE
  AttributeError: type object 'App' has no attribute 'from_config'

### ISSUE THREAD

**Issue by srj-krishna** [embedchain/embedchain#1269]
Not being able to load custom configurations .

app = App.from_config('config.yaml')

AttributeError: type object 'App' has no attribute 'from_config'

**Comment by deshraj** [comment]
@srj-krishna can you please clarify which embedchain version you are using?

You can check the version with 

```python
import embedchain
print(embedchain.__version__)
```

**Comment by pratikdel04** [comment]
Use Python 3.10 or above it works fine for it

**Comment by pratikkotian04** [comment]
Facing Same issue. Using Latest Version of embedchain with streamlit

**Comment by Dev-Khant** [comment]
Hi @srj-krishna @pratikkotian04  Please try using python >= 3.10 and latest embedchain version. Let us know if it still doesn't work.

**Comment by jmanali1996** [comment]
@Dev-Khant thank you so much for the solution. It worked for me!
