### ISSUE TITLE
[Thoughts] Real docs instead of readme

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#128]
The readme is getting really long, maybe we should use a real documentation, maybe something like the langchain docs? (what software is that?)

**Comment by aaishikdutta** [comment]
I think they use Docusaurus

**Comment by aaishikdutta** [comment]
Do we want this on a separate repo?

**Comment by taranjeet** [comment]
@deshraj also had some input.
I was thinking of https://mintlify.com/
I would suggest that all 4 of us should get on a call or discuss here and then close the implementation details.

@cachho @aaishikdutta @deshraj @taranjeet

**Comment by aaishikdutta** [comment]
Sure

**Comment by cachho** [comment]
> I was thinking of https://mintlify.com/

Isn't that closed source?

The main feature I want is the option to have a code snippet that can be switched between python/js/ts so that we have less to manage.

**Comment by deshraj** [comment]
I tried a bunch of libraries and looks like mintlify seems like a reasonable one to use. We should set it up. I will go ahead and setup the base project so that we can stop cluttering the README.

**Comment by aaishikdutta** [comment]
Can you share the repository, would like to contribute

**Comment by deshraj** [comment]
@aaishikdutta will share soon.
