### ISSUE TITLE
Facing issue with quick start guide

### ISSUE THREAD

**Issue by taham655** [embedchain/embedchain#1304]
### 🐛 Describe the bug

I'm getting the following error everytime i try to run the quick start guide that you have shared in the docs. 

'Inserting batches in chromadb:   0%|          | 0/1 [00:02<?, ?it/s]Failed to add batch due to a bad request: Connection error.
Successfully saved https://www.forbes.com/profile/elon-musk (DataType.WEB_PAGE). New chunks count: 0

8cf46026cabf9b05394a2658bd1fe890'

**Comment by deshraj** [comment]
Hey, it seems to be working on my end. Seems like it might have been a transient issue. Can you please try again and confirm?

**Comment by deshraj** [comment]
Closing this issue for now. please feel free to reopen if the issue persists.
