### ISSUE TITLE
Error Handling (Empty Database)

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#131]
We have to come up with a way to handle errors.

The most common issue is 
```
retrieve_from_database
    content = result_formatted[0][0].page_content
```

**Comment by taranjeet** [comment]
Discord messages:
- https://discord.com/channels/1121119078191480945/1121119078858358846/1125847354281558036
- https://discord.com/channels/1121119078191480945/1121119078858358846/1125841669640700065

**Comment by taranjeet** [comment]
will add my thoughts on this in sometime.

**Comment by cachho** [comment]
Closing this, because I guess thinking about it again, it should be possible to query an empty database, might be better for dry runs.
