### ISSUE TITLE
Add support for Azure AI Search Vector Store

### ISSUE THREAD

**Issue by pratikdel04** [embedchain/embedchain#1330]
### 🚀 The feature

This feature request proposes adding support for Azure AI Search Vector Store as a backend storage option for embedchain. Embedchain currently supports various storage backends like Faiss, Annoy, and Milvus. Integrating Azure AI Search would provide users with a managed cloud-based solution for vector storage and retrieval.

### Motivation, pitch

Many users leverage Azure cloud services for their applications. Having Azure AI Search support in embedchain would streamline the integration process for these users by allowing them to utilize a familiar and managed service for vector storage. Additionally, Azure AI Search offers features like scalability, geo-replication, and built-in query capabilities that could benefit embedchain users.

Benefits

Simplified Integration: Users working with Azure services can seamlessly integrate embedchain with their existing infrastructure.
Managed Service: Azure AI Search handles the underlying infrastructure, reducing maintenance overhead for users.
Scalability: Azure AI Search scales to meet the growing needs of the application.
Geo-replication: Enables geographically distributed deployments for improved redundancy and disaster recovery.
Query Capabilities: Leverages Azure AI Search's built-in query functionalities for efficient vector retrieval.

**Comment by Dev-Khant** [comment]
Hi @pratikdel04 there's already an open issue for adding Azure AI Search as vector DB #1119
