### ISSUE TITLE
Getting Input validation error while using "Chat" function of embedchain

### ISSUE THREAD

**Issue by mdevs7** [embedchain/embedchain#1338]
### 🐛 Describe the bug

Here is my code which is producing the error.
```
import os
from embedchain import App

# Replace this with your OpenAI key
os.environ["OPENAI_API_KEY"] = "sk-AFj3XbMaBfuTjzAsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

app = App()
app.add("https://www.forbes.com/profile/elon-musk")
app.add("https://en.wikipedia.org/wiki/Elon_Musk")
app.query("What is the net worth of Elon Musk today?")

answer, sources = app.chat("What is the net worth of Elon?", citations=True)
print(answer)
print(sources)
```
When I am using the `chat()` method to query from data source then throwing an error of rate limit as here : 
`'Request too large for gpt-3.5-turbo in organization org-PzDzUDWjyxxxxxxxxxxxxxxxx on tokens per min (TPM): Limit 40000, Requested 55065. The input or output tokens must be reduced in order to run successfully.`

This same error is not produced while using `search()` or `query()` function for query from data source.

Here is full log:
File "C:\Users\admin\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 1013, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Request too large for gpt-3.5-turbo in organization org-PzDzUDWjyxxxxxxxxxxxxx on tokens per min (TPM): Limit 40000, Requested 55065. The input or output tokens must be 
reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

**Comment by LeonieFreisinger** [comment]
@mdevs7 Have you solved the error yet? 
I ran your code but did not run into an error. 
In case it still occurs, have you updated to the latest embedchain and openai version?

**Comment by Dev-Khant** [comment]
@mdevs7 Closing this issue as it's not faced in the latest embedchain version and it looks like issue is more related to your Openai API limits.
This might help you: https://community.openai.com/t/rate-limit-error-tier-2-account-rate-limit-issues-with-gpt-3-5-turbo/577906/4
