### ISSUE TITLE
AzureOpenAI features not supported and are hard coded

### ISSUE THREAD

**Issue by neilbhutada** [embedchain/embedchain#1347]
### 🐛 Describe the bug

In the documentation and the code base there seems to be a discrepancy. In the documentation, it says to use the following environment variables while using AzureOpenAI services, but the name of the environment variables differs. Secondly, I was looking at the source code and it seems that the api version was hard coded. It would be nice to pull the from yaml config. Thirdly, I couldn't see the embedder for AzureOpenAI in the source code.
Thank you!

**Comment by pratikkotian04** [comment]
Facing same issue

**Comment by denaha** [comment]
I was able to load the version from the YAML config, in the latest version, below an example how it worked.

`os.environ["OPENAI_API_VERSION"] = "2024-02-01"`

**Comment by PranavPuranik** [comment]
I will take this up

**Comment by PranavPuranik** [comment]
@neilbhutada 

My PR will fix the mismatch in the documentation for azure openai environment variables, and let you add `api_version` from the config.

Azure OpenAI embedder is already present in the [code](https://github.com/embedchain/embedchain/blob/main/embedchain/embedder/openai.py#L23) and [docs](https://docs.embedchain.ai/components/embedding-models#azure-openai). You can put your deployment name in config and use it. 

However, I feel it should be in a different file such as `embedders/azure_openai.py`, and `self.config.deployment_name` should not be used to differentiate between azure and openai embedded. @Dev-Khant let me know if you think the same, will make that change.

Please let me know if you have any other issues.
