### ISSUE TITLE
PyPDF version Update

### ISSUE THREAD

**Issue by amjadraza** [embedchain/embedchain#1351]
### 🚀 The feature

Can we upgrade the `pypdf` version to >4.0.1

pypdf = "^3.11.0"

### Motivation, pitch

Since CrewAI depends on EmbedChain, we are unable to install llama-index

And because embedchain (0.1.102) depends on pypdf (>=3.11.0,<4.0.0), crewai (>=0.28.8,<0.29.0) requires pypdf (>=3.11.0,<4.0.0).
    And because llama-index (>=0.10.33,<0.11.0) requires pypdf (>=4.0.1,<5.0.0) (1), llama-index (>=0.10.33,<0.11.0) is incompatible with crewai (>=

**Comment by deshraj** [comment]
Yes, let me upgrade tonight.

**Comment by deshraj** [comment]
Released version 0.1.103 that fixes this issue.

**Comment by amjadraza** [comment]
@deshraj thanks cheers
