### ISSUE TITLE
http_client variable not available in OpenAILlm class

### ISSUE THREAD

**Issue by AbdurNawaz** [embedchain/embedchain#1357]
### 🚀 The feature

embedchain uses Langchain's ChatOpenAI class behind the scenes for its openai llm configuration but does not expose some of the useful fields available in ChatOpenAI. For eg., the http_client variable that can be used to add proxy configuration to connect to openai LLMs is not available through embedchain's interface.

I have raised a PR for the same #1355 . I can also tweak it to support all Langchain's params if the devs are okay with it.

### Motivation, pitch

To be able to have fine grained control over OpenAi LLM interactions like proxies, SSL config, additional headers.

**Comment by PranavPuranik** [comment]
Hi @AbdurNawaz,

Could you please send a sample usage?
