### ISSUE TITLE
Support Hebrew?

### ISSUE THREAD

**Issue by moshere-cirm** [embedchain/embedchain#1358]
### 🚀 The feature

Hi,
Are you supporting Hebrew? If yes any special configuration is needed?

Thanks!

### Motivation, pitch

Hi,
Are you supporting Hebrew? If yes any special configuration is needed?

Thanks!

**Comment by deshraj** [comment]
Hey, we don't have to explicitly support the hebrew language since most of the LLMs already work with it. Closing this issue for now.
