### ISSUE TITLE
How to save and load a database to local

### ISSUE THREAD

**Issue by zhouyongxiu** [embedchain/embedchain#1361]

**Comment by deshraj** [comment]
Hey @zhouyongxiu, can you please elaborate more about the issue? It is not clear what the feature request is. Please feel free to add a description to your issue.

**Comment by zhouyongxiu** [comment]
Sometimes, after I use bot.add() some data to database, I want to save the database to local disk, just like "bot.save()", when I use the bot next time, I can just load the bot like "bot.load", and would not use bot.add() again.

**Comment by zhouyongxiu** [comment]
thanks
