### ISSUE TITLE
version mismatch langhchan-openai 

### ISSUE THREAD

**Issue by amjadraza** [embedchain/embedchain#1363]
### 🐛 Describe the bug

With new version `of `langchain-openai (^0.1.6)`, embedchain is not working 

Because no versions of embedchain match >0.1.103,<0.2.0
 and embedchain (0.1.103) depends on langchain-openai (>=0.0.5,<0.0.6), embedchain (>=0.1.103,<0.2.0) requires langchain-openai (>=0.0.5,<0.0.6).
So, because giospatial-tl-report depends on both langchain-openai (^0.1.6) and embedchain (^0.1.103), version solving failed.

**Comment by deshraj** [comment]
Thanks @amjadraza for creating the issue. Will fix it in few hours.

**Comment by AndreaLombax** [comment]
Still the same problem, any updates?
Otherwise I will be forced to remove from my project all the parts that includes embedchain, it looks like a stillborn library.

**Comment by deshraj** [comment]
Sorry for the delay guys. We have been quite swamped with a lot of other stuff. Working on a fix right now. Will put up a PR soon.
