### ISSUE TITLE
ImportError: cannot import name 'MessageContentText' from 'openai.types.beta.threads'

### ISSUE THREAD

**Issue by utkarsh27a** [embedchain/embedchain#1369]
#### Description:
When using OpenAI version > 1.13.4 in pip dependencies, the following error occurs:

```
ImportError: cannot import name 'MessageContentText' from 'openai.types.beta.threads'
```

This error arises because `MessageContentText` is not present in `openai.types.beta.threads`.

#### Steps to Reproduce:
1. Use OpenAI assistants.
2. Import `OpenAIAssistant` using:
   ```python
   from embedchain.store.assistants import OpenAIAssistant
   ```
3. The error mentioned above will be triggered.

Please ensure the OpenAI version in your dependencies is <= 1.13.4 to avoid this issue.

**Comment by jstnmthw** [comment]
It looks like they changed up the typing to do unions of Image and Text on `MessageContent`

You can take a look at these types: MessageContent and TextContentBlock

```
from openai.types.beta.threads.message_content import MessageContent
from openai.types.beta.threads.text_content_block import TextContentBlock
```

In my case, I had to update:

From:
`if isinstance(messages.data[0].content[0], MessageContentText):`

To:
`if isinstance(messages.data[0].content[0], TextContentBlock):`
