### ISSUE TITLE
Unable to access Ollama embedding model on remote machine

### ISSUE THREAD

**Issue by dpatschke** [embedchain/embedchain#1390]
I have Ollama running on a remote machine which I am attempting to access with embedchain, in particular the embedding model.  

It appears that the following line of code is calling the ollama library that, by default, attempts to list the models on the local machine running ollama rather than leveraging the `base_url` being assigned to the `base_url` property of the `OllamaEmbedderConfig` object being created.

Below is my embedder config dictionary I am using:
```
"embedder": {
        "provider": "ollama",
        "config": {
            "model": "mxbai-embed-large:latest",
            "base_url": "http://10.0.0.24:11434"
        }
    }
```

Below is debug showing that the property is being set:
```
ipdb>  self.config
<embedchain.config.embedder.ollama.OllamaEmbedderConfig object at 0x7b73dfe31350>
ipdb>  self.config.base_url
'http://10.0.0.24:11434/'
```
Below is the `GET` request being made by the referenced code line:
```
> /opt/conda/envs/embedchain/lib/python3.11/site-packages/embedchain/embedder/ollama.py(22)__init__()
     20         super().__init__(config=config)
     21 
---> 22         local_models = ollama.list()["models"]
     23         if not any(model.get("name") == self.config.model for model in local_models):
     24             logger.info(f"Pulling {self.config.model} from Ollama!")

/opt/conda/envs/embedchain/lib/python3.11/site-packages/ollama/_client.py(333)list()
    331 
    332   def list(self) -> Mapping[str, Any]:
--> 333     return self._request('GET', '/api/tags').json()
    334 
    335   def copy(self, source: str, destination: str) -> Mapping[str, Any]:

> /opt/conda/envs/embedchain/lib/python3.11/site-packages/httpx/_client.py(827)request()
    825             extensions=extensions,
    826         )
--> 827         return self.send(request, auth=auth, follow_redirects=follow_redirects)
    828 
    829     @contextmanager

ipdb>  request
<Request('GET', 'http://127.0.0.1:11434/api/tags')>
```

Please let me know if there is any additional details I need to provide.

https://github.com/embedchain/embedchain/blob/04e77ef34eaf91a566f3e06f7965550d0df007b5/embedchain/embedder/ollama.py#L22

**Comment by Dev-Khant** [comment]
Hi @dpatschke My bad I missed that part. This PR will fix it.
Thanks for pointing this out!
