### ISSUE TITLE
bad request error when using GET query method of rest-api docker

### ISSUE THREAD

**Issue by jonabert** [embedchain/embedchain#1412]
Error: Bad Request
Response body

{
  "detail": "Error occurred: App.from_config() got an unexpected keyword argument 'config_path'"
}
![image](https://github.com/embedchain/embedchain/assets/5072157/15e0d72c-2800-4fe7-b741-123e881bdb8e)

**Comment by Dev-Khant** [comment]
@jonabert Please upgrade embedchain to the latest version. Let us know if it doesn't work.
