### ISSUE TITLE
obvious characters that are very common on huggingface not allowed

### ISSUE THREAD

**Issue by jonabert** [embedchain/embedchain#1419]
### 🐛 Describe the bug

/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/langchain_core/_api/deprecation.py:119: LangChainDeprecationWarning: The class `HuggingFaceHub` was deprecated in LangChain 0.0.21 and will be removed in 0.3.0. Use HuggingFaceEndpoint instead.
  warn_deprecated(
Error during chat: 1 validation error for HuggingFaceHub
__root__
  Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'Mistral-7B-v0.1:latest'. (type=value_error.hfvalidation)

**Comment by Dev-Khant** [comment]
@jonabert Please can you try upgrading huggingface_hub `pip install --upgrade huggingface_hub` and let us know if it works?

**Comment by jonabert** [comment]
works
