### ISSUE TITLE
[BUG] ImportError: cannot import name 'OpenSourceApp' from 'embedchain' (/environment/miniconda3/lib/python3.7/site-packages/embedchain/__init__.py)

### ISSUE THREAD

**Issue by TommyZihao** [embedchain/embedchain#148]
ImportError: cannot import name 'OpenSourceApp' from 'embedchain' (/environment/miniconda3/lib/python3.7/site-packages/embedchain/__init__.py)

<img width="1172" alt="image" src="https://github.com/embedchain/embedchain/assets/36354458/1f0e8c4e-06e7-4b96-ac12-383920d13683">

**Comment by cachho** [comment]
are you sure you have the latest version installed? this is a new feature.

**Comment by taranjeet** [comment]
Hey @chetansharma47 , can you please share the version installed?
