### ISSUE TITLE
ValueError: No corresponding model for provided filename orca-mini-3b.ggmlv3.q4_0.bin. 

### ISSUE THREAD

**Issue by akashlinux10may** [embedchain/embedchain#149]
ValueError: No corresponding model for provided filename orca-mini-3b.ggmlv3.q4_0.bin.
            If this is a custom model, make sure to specify a valid model_type.

any resolution. I was trying the following code after installing embedchain

from embedchain import OpenSourceApp

naval_chat_bot = OpenSourceApp()
naval_chat_bot.add("pdf_file", "xyz.pdf")
print(naval_chat_bot.query("how many states are there in India?"))

**Comment by cachho** [comment]
Can you try again with the latest version? This should be resolved, the whole process has been streamlined, just make sure you use the right app type. If you still have any issues, please reopen.
