### ISSUE TITLE
[REFACTOR] Config

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#156]
With all the PRs and Issues, it has become obvious that we as maintainers need to decide on a way to configure embedchain.

**Comment by cachho** [comment]
1. **Passing a dictionary of options to the method**: This approach is simple, flexible and makes it clear which options are being used for each individual call to the `query` method. 

    Here's an example:

    ```python
    naval_chat_bot.query(
        "What unique capacity does Naval argue humans possess when it comes to understanding explanations or concepts?", 
        options={"num_documents": 5, "llm_model": "chatgpt-3.5"}
    )
    ```

    In the `query` method, you'd unpack the `options` dictionary like so:

    ```python
    def query(self, question, options=None):
        if options is None:
            options = {}
        num_documents = options.get('num_documents', 1)
        llm_model = options.get('llm_model', 'default_model')
        # ...
    ```

2. **Using a configuration class**: This is a more structured approach that provides a clear definition of what the configuration options are, and makes it easy to provide default values for those options. It also allows you to add methods to the configuration class to manipulate or validate the configuration data.

    Here's how you'd use a configuration class:

    ```python
    class QueryConfig:
        def __init__(self, num_documents=1, llm_model='default_model'):
            self.num_documents = num_documents
            self.llm_model = llm_model

    config = QueryConfig(num_documents=5, llm_model="chatgpt-3.5")
    naval_chat_bot.query("What unique capacity does Naval argue humans possess when it comes to understanding explanations or concepts?", config)
    ```

    In the `query` method, you'd access the properties of the `config` object:

    ```python
    def query(self, question, config=None):
        if config is None:
            config = QueryConfig()
        num_documents = config.num_documents
        llm_model = config.llm_model
        # ...
    ```
    
    3. **Using setter methods in the class**: This approach involves changing the state of the `App` object itself. This makes it easy to change the configuration dynamically without having to pass in the same configuration options every time you make a query. However, it also means that the configuration persists across multiple queries.

    Here's an example:

    ```python
    class App:
        def __init__(self):
            self.config = QueryConfig()

        def set_num_documents(self, num_documents):
            self.config.num_documents = num_documents

        def set_llm_model(self, llm_model):
            self.config.llm_model = llm_model

        def query(self, question):
            num_documents = self.config.num_documents
            llm_model = self.config.llm_model
            # ...

    naval_chat_bot = App()

    naval_chat_bot.set_num_documents(5)
    naval_chat_bot.set_llm_model("chatgpt-3.5")

    naval_chat_bot.query("What unique capacity does Naval argue humans possess when it comes to understanding explanations or concepts?")
    ```

**Comment by cachho** [comment]
Maintainers have decided to roll with variant 2.

**Comment by cachho** [comment]
PR is ready, #158

**Comment by taranjeet** [comment]
@cachho : feel free to close this if everything is addressed.
For ChatConfig, I have created a new issue https://github.com/embedchain/embedchain/issues/167 to track.

**Comment by cachho** [comment]
closing this because all configs so far exist. If there are questions regarding chat, tracking in #167.
