### ISSUE TITLE
Add config support for chat endpoint.

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#167]
- like we added support for init, add and query, we should add support for chat endpoint.
- PR which adds support for init, add and query: https://github.com/embedchain/embedchain/pull/158

**Comment by taranjeet** [comment]
cc @cachho we can leave this issue for sometime. It can be a good first issue for anyone new to the project.

**Comment by cachho** [comment]
there is a `ChatConfig.py`. Or what do you mean?

**Comment by gasolin** [comment]
@cachho @taranjeet currently we have 3 similar stuff
- query: one time query, use QueryConfig
- chat: query with history, use ChatConfig
- dryrun: show query prompt, no Config

feel they could all share the same `QueryConfig` to reduce the complexity

**Comment by cachho** [comment]
fixed
