### ISSUE TITLE
Issue on TypeVar

### ISSUE THREAD

**Issue by big-analytics** [embedchain/embedchain#17]
When trying to run the sample code I get this:
ImportError: cannot import name 'TypeVar' from 'typing_extensions' (/databricks/python/lib/python3.10/site-packages/typing_extensions.py)

I am running this in a Databricks notebook.

**Comment by taranjeet** [comment]
Hey @big-analytics , sorry that you had to face an error. Can you try [this answer](https://stackoverflow.com/a/69318524/2534102) and let me know if it works?

**Comment by big-analytics** [comment]
That seemed to do the trick. Thanks for that. I had to restart python in Databricks.

**Comment by big-analytics** [comment]
Thanks for the quick help.
