### ISSUE TITLE
Slow response for OpenSourceApp() [cpu]

### ISSUE THREAD

**Issue by PaulCristina** [embedchain/embedchain#186]
It takes a very long time to get the response with OpenSourceApp from embedchain==0.0.17, around 100 secs, is this normal?

![image](https://github.com/embedchain/embedchain/assets/31437758/bbd31836-c7dd-419e-aed8-c8f229edd0cd)

**Comment by Dev-Khant** [comment]
Closing this issue as `OpenSourceApp` is no longer available.
