### ISSUE TITLE
DuplicateIDError when trying to load a particular training data

### ISSUE THREAD

**Issue by Rishab-Haltore** [embedchain/embedchain#187]
Firstly, i really loved the framework. There is one issue when i use it for my use case which is when i try to load a training data which can have duplicate entries: I get this error:
naval_chat_bot.add("pdf_file","/content/training_data.pdf")

Error:
DuplicateIDError                          Traceback (most recent call last)
[<ipython-input-6-da23df8565b5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 naval_chat_bot.add("pdf_file","/content/training_data.pdf")

3 frames
[/usr/local/lib/python3.10/dist-packages/chromadb/api/types.py](https://localhost:8080/#) in validate_ids(ids)
    115     if len(ids) != len(set(ids)):
    116         dups = set([x for x in ids if ids.count(x) > 1])
--> 117         raise errors.DuplicateIDError(
    118             f"Expected IDs to be unique, found duplicates for: {dups}"
    119         )
    
    
    i think the embedchain is using a unique identifier(hash) to manage and index the data. Is it possible to overcome this without having to change or format the dataset.
    
    Thank you

**Comment by cachho** [comment]
#64 we're tracking this already. fix #160 is on the way. closing this.
