### ISSUE TITLE
[Feature Request] add json/jsonl as data_type

### ISSUE THREAD

**Issue by Rishab-Haltore** [embedchain/embedchain#188]
Thank you

**Comment by cachho** [comment]
don't you think you'd have an easier time destructuring the json on your end and only passing what you really need to `add_local("text", ...)`? If we just dump a whole json file it will include ids and all kinds of stuff you will never ask the bot for.

But I get if you're just trying to ingest as much data from online sources, with "0 touch", yes, then it makes sense.

We'll keep this open, I think we'll add the feature in the not so distant future, but in the meantime please consider parsing the json yourself. You might find the results to be better.

**Comment by Rishab-Haltore** [comment]
What you said makes sense but the use case that I have is a bit different.
Lets say with a bit of prompt engineering. We have a file / training data containing prompts ans competions in a single json/jsonl file(1gb or less). For example:
{"prompt": "<prompt text>", "completion": "<ideal generated text>"}
{"prompt": "<prompt text>", "completion": "<ideal generated text>"}
{"prompt": "<prompt text>", "completion": "<ideal generated text>"}
...

or a little format . How do we achive this with the current framework since there is no support for json/json as data_type

@cachho let me know if it makes sense. Thanks

**Comment by cachho** [comment]
@Rishab-Haltore we already have QnA as an abstraction of pairs. You wouldn't want use to embed {"prompt": "", "completion": ""}, right? You would want us to embed something like "prompt: ..., completion: ...". Compared to QnA, I feel like this is a very individual layout and not something we can provide a standard format for.

Why don't you loop through the json and insert each row with `local_add("text", ...)`? Then you can design the embedding as you like.

**Comment by Rishab-Haltore** [comment]
Cool. Makes sense
