### ISSUE TITLE
Feature Request - Integrate Azure's OpenAI API as an Option

### ISSUE THREAD

**Issue by big-analytics** [embedchain/embedchain#19]
Currently, embedchain is designed to use OpenAI's API for creating embeddings and leveraging the power of GPT-3 for generating answers in the context of chatbots. This feature request proposes to include the option of using Azure's OpenAI API as an alternative.

Azure, a comprehensive suite of cloud services offered by Microsoft, also provides an implementation of OpenAI API. Integration with Azure's OpenAI API would provide a choice to the users to select between OpenAI's original API and Azure's version based on their specific requirements and preferences.

**Comment by xihuishawpy** [comment]
Can modify the source code of the API configuration.

**Comment by aaishikdutta** [comment]
@big-analytics @xihuishawpy please check the above PR, you can use Azure OpenAI as following:
1) In addition to OpenAI key add API base in environment as : OPENAI_API_BASE
2) add is_azure=True in InitConfig

Please test this out if you have Azure OpenAI keys

**Comment by taranjeet** [comment]
this is addressed now. Closing the issue.
