### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by Dhravya** [embedchain/embedchain#194]
I'm trying to build an app based on open-source models using Embedchain. Is it possible to support multiple languages like Hindi, Hinglish etc.?

**Comment by cachho** [comment]
Doesn't chatgpt have that capability out of the box?

**Comment by deshraj** [comment]
@Dhravya, as @cachho mentioned, ChatGPT supports multiple languages and it should work just fine. Please feel free to reopen the issue if you need help after trying out chatgpt.
