### ISSUE TITLE
Custom Model / GPT4all model.

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#197]
Hey @taranjeet I loved embedchain and wanted to use it in one of my projects. I wanted to use my custom model / GPT4All models, do you have any documentation related to it?
Current default model is all-MiniLM-L6-v2
- discord message link: https://discord.com/channels/1121119078191480945/1121119078858358846/1127139683953025094

**Comment by TomasTomecek** [comment]
I second this ask. Unfortunately all-MiniLM-L6-v2 can only work with 256 tokens which is fairly limiting. GPT4All's default embedding model (ggml-all-MiniLM-L6-v2-f16) can do even several k so it would be amazing to use it.

```
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: ...)

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/ggml-all-MiniLM-L6-v2-f16.
```

**Comment by nav9** [comment]
Using embedChain with GPT4All is something I'm looking forward to as well.

**Comment by Dev-Khant** [comment]
Closing this issue as GPT4All functionality is more robust now and can handle different models. Please feel free to open this issue again if there's still a problem.
