### ISSUE TITLE
[Bug] app.reset() Function Doesn't Exist

### ISSUE THREAD

**Issue by jessekirbs** [embedchain/embedchain#218]
Trying to utilized the app.reset() function, but I get the following error:

`AttributeError: 'App' object has no attribute 'reset'`

Any suggestions would be greatly appreciated. Thanks!

**Comment by ahnedeee** [comment]
app should be the name of the instance of the App class

**Comment by ahnedeee** [comment]
meaning if you have 'chat_bot = App()' you should do 'chat_bot.reset()' not 'app.reset()'

**Comment by jessekirbs** [comment]
> meaning if you have 'chat_bot = App()' you should do 'chat_bot.reset()' not 'app.reset()'

Hey @ahnedeee - thanks for the response. That's what I did and the error was the one I listed above. Is it working for you?

**Comment by cachho** [comment]
Please post the whole script and the output. Include InitConfig(log_level="DEBUG")

**Comment by ahnedeee** [comment]
> 

it works for me

**Comment by jessekirbs** [comment]
> InitConfig(log_level="DEBUG")

Hey @cachho, here's the code:

`import typing
from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QPlainTextEdit, QFileDialog
from PyQt5 import QtCore, uic
import sys
from dotenv import load_dotenv

load_dotenv()

from embedchain import App

embed_bot = App()
embed_bot.reset()

class UI(QMainWindow):
    def __init__(self):
        super(UI, self).__init__()

        #Load the UI file
        uic.loadUi("embedbot_UI.ui", self)

        # Define widgets
        self.fileBrowseButton = self.findChild(QPushButton, "pushButton")
        self.fileBrowseText = self.findChild(QPlainTextEdit, "fileBrowseText")
        self.pushButton_Add_PDF = self.findChild(QPushButton, "pushButton_Add_PDF")
        self.questionText = self.findChild(QPlainTextEdit, "questionText")
        self.pushButton_Ask = self.findChild(QPushButton, "pushButton_Ask")
        self.responseText = self.findChild(QPlainTextEdit, "responseText")

        #Widget functionality
        self.fileBrowseButton.clicked.connect(self.fileBrowse)
        self.pushButton_Add_PDF.clicked.connect(self.addPDF)
        self.pushButton_Ask.clicked.connect(self.askQuestion)

        #Show the app
        self.show()

    def fileBrowse(self):
        #Open file dialog
        global fname
        fname = QFileDialog.getOpenFileName(self, "Select PDF...", "", "PDF (*.pdf)")

        #Output filename to text box
        if fname:
            self.fileBrowseText.setPlainText(fname[0])

    def addPDF(self):
        #Add PDF to embedchain database
        embed_bot.add("pdf_file", fname[0])

    def askQuestion(self):
        #Get question text
        questionTextData = self.questionText.toPlainText()
        print(questionTextData)
        answer = embed_bot.query(questionTextData)
        self.responseText.setPlainText(answer)


#Initialize the app
embedBotApp = QApplication(sys.argv)
UIWindow = UI()
embedBotApp.exec_()`

I'm new to Python, and I'm having trouble finding info about how to use InitConfig(log_level="DEBUG"). Can you please elaborate on how I should utilize that? Thank you!

**Comment by cachho** [comment]
```python
from embedchain import App
from embedchain.config import InitConfig

config  = InitConfig(log_level="DEBUG")
embed_bot = App(config)
```

please include the whole output. 

What version of embedchain are you using?

**Comment by jessekirbs** [comment]
I added the above code and am now receiving this error:

`ModuleNotFoundError: No module named 'embedchain.config'`

I'm using embedchain 0.0.18

**Comment by cachho** [comment]
Please upgrade to the latest version

**Comment by jessekirbs** [comment]
> Please upgrade to the latest version

Upgraded to 0.0.21 - still experiencing the same issues.

**Comment by cachho** [comment]
> Upgraded to 0.0.21 - still experiencing the same issues.

I copied your code and it works for me.

**Comment by cachho** [comment]
can you print out your `app` variable? Maybe pyqt introduces some global variable with the same name. That's the only thing I can think of.

**Comment by jessekirbs** [comment]
That's strange.

print(app) gives me 'NameError: name 'app' is not defined. Did you mean: 'App'?'

print(App) gives me: <class 'embedchain.embedchain.App'>

Is there a method for verifying that embedchain was installed correctly? Not sure what else it could be.

**Comment by cachho** [comment]
> That's strange.
> 
> `print(app)` gives me `NameError: name 'app' is not defined. Did you mean: 'App'?`

No I mean `embed_bot`
