### ISSUE TITLE
[Query] Is it possible to create multiple instances and if so how to retrieve it ?

### ISSUE THREAD

**Issue by techguruagi** [embedchain/embedchain#223]
My requirement is as below

I'd like to create separate bots for my YouTube links, Wikipedia links, Local PDFs. Am planning to index all the existing resources once and then later add new resources whenever available. 

How to create multiple instances, update and retrieve records ?. Any help is appreciated.

**Comment by cachho** [comment]
PR #189 implements this

**Comment by cachho** [comment]
You can create multiple instances of the app class. With the collection name keyword they can use different collections of data. Where filtering can be improved definitely, but I think it's at a point where this ticket can be closed.
