### ISSUE TITLE
Import app is taking longer to complete

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#225]
* Create a new virtual environment and install embedchain

```
pip install embedchain
```

* Now open python shell and run
```
from embedchain import App
```

It is taking around 5-7 seconds for the load to be finished.

We should find out why is it taking so long.

**Comment by cachho** [comment]
can't confirm. Tried with 0.0.19 from pip.

```
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> s = time.perf_counter(); from embedchain import App; time.perf_counter()-s
1.0395880700016278
```

**Comment by deshraj** [comment]
@taranjeet I think I am seeing similar pattern as @cachho mentioned. The package import seems quite fast for now. Please feel free to reopen if you see high import time.
