### ISSUE TITLE
[Feature Request] Add support for reading audio URL (podcast/music/mp3)

### ISSUE THREAD

**Issue by heaversm** [embedchain/embedchain#240]
I'm currently manually loading, chunking, and writing buffers for mp3 files retrieved via RSS urls. Would be great to use the abstractions from embedchain to just call `.add("audio_url","https://mypodcasthost.com/mypodcast/myepisode.mp3")`

**Comment by cachho** [comment]
How do you want to convert to chunkable text?

**Comment by Dev-Khant** [comment]
Hi @heaversm, we have the capability to process audio files that can accept both a file path and an audio URL. Check out the documentation here: https://docs.embedchain.ai/components/data-sources/audio.
