### ISSUE TITLE
Chunker's size default should set below 256 or even more for opensource embeddings?

### ISSUE THREAD

**Issue by YunchengLiang** [embedchain/embedchain#255]
Default values of chunker config parameters for different data_type:
data_type	chunk_size	chunk_overlap	
docx	      1000	                  0	                 
text	               300	                  0	                
qna_pair	       300	                  0	
web_page       500	                  0	
pdf_file	      1000	                  0	
youtube_video 2000	          0	 

Embedchain chooses to use "all-MiniLM-L6-v2" for text embeddings if taking opensource option.
However, according to the hugging face documentation of opensource embedding "all-MiniLM-L6-v2", it says "By default, input text longer than 256 word pieces is truncated."
Does that means if i do not change the chunk size for pdf file(default chunk size 1000) to be lower than 256 tokens and less if in words count, all the rest of the tokens will be truncated and would result in poor performance during the search since each embedding is not representative of the chunk it belongs too.

Please help me with this concern and thank you very much.

**Comment by cachho** [comment]
The defaults are just vague guesses. For all of these formats, you will find items of different sizes, with different content, that requires different chunking. We do have config options for that, please follow the readme (#251)

What you're saying is that 256 should be the max for the open source model. We can consider setting different defaults for that.

**Comment by YunchengLiang** [comment]
> The defaults are just vague guesses. For all of these formats, you will find items of different sizes, with different content, that requires different chunking. We do have config options for that, please follow the readme (#251)
> 
> What you're saying is that 256 should be the max for the open source model. We can consider setting different defaults for that.

Thank you very much, I will then set the input chunk size to be lower than 256 for all formats through config, have a wonderful day!
