### ISSUE TITLE
Frontend Python or JS

### ISSUE THREAD

**Issue by mynumu** [embedchain/embedchain#256]
Hello. Not an issue but a question. Love this. What does anyone recommend a front end for this and is it better to run this in js or python. I have a local python install for now but want to create some sort of gui front end. Am a very low coder so do you need an API or is there another way. Thanks

**Comment by cachho** [comment]
My experience (and I say that as a Flask Base contributor) is that Python in the browser is ways behind JS. 

I put my embedchain behind Flask with Gunicorn in the backend, and NextJS in the frontend. The chat window is based on https://github.com/zahidkhawaja/langchain-chat-nextjs but highly modified to include welcome messages and history.

We have our own template that you can try, I haven't tried it myself.: https://github.com/embedchain/qna-bot-template-js

**Comment by mynumu** [comment]
Thanks for taking the time to reply. I will see if I can get the js template running. Do you have discord/other place to ask questions/community shares etc. thanks

**Comment by taranjeet** [comment]
Hey @mynumu : please find our discord here: https://discord.com/invite/6PzXDgEjG5
