### ISSUE TITLE
[Query] Is there a method for deleting docs/links/etc. in the vector database?

### ISSUE THREAD

**Issue by jessekirbs** [embedchain/embedchain#257]
Is there a way to delete certain/all items (uploaded PDFs, YouTube links, etc.) in the vector database (besides the app.reset() function)?

**Comment by cachho** [comment]
It should be by using app.db_client and then Chroma's delete method that you can find in the chroma docs.

**Comment by cachho** [comment]
but I also had the idea, which you probably want, to automatically add a metatag for the loader used. I will open an Issue for this.

**Comment by jessekirbs** [comment]
Thanks, @cachho. Does embedchain automatically create and name a Chroma db collection when you add the first data? If so, what is the collection called?

**Comment by cachho** [comment]
> what is the collection called?

`embedchain_store`

https://github.com/embedchain/embedchain/blob/8f42ced9b590d30b3abf4303fda5a19e828cc41e/embedchain/vectordb/chroma_db.py#L47C15-L47C15

**Comment by cachho** [comment]
Tracking this issue with #387. Closing this.
