### ISSUE TITLE
[Feature Request] Automatically add Loader/Format used to Metadata

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#258]
This allows to target a certain kind for deletion.

For instance, you could renew your QnA pair embeddings, while leaving YouTube videos intact.

**Comment by jessekirbs** [comment]
Would this be the best method for turning certain items on/off for queries? For example, I'd like to have a list of the items that have been loaded into the database with checkboxes next to them, and you can check/uncheck the items you wish embedchain to include in queries. 

I was going to try to do this by deleting the items from the Chroma db, but the IDs and such are all named long strings and I'm not sure how to delete a specific item.

**Comment by cachho** [comment]
> Would this be the best method for turning certain items on/off for queries? For example, I'd like to have a list of the items that have been loaded into the database with checkboxes next to them, and you can check/uncheck the items you wish embedchain to include in queries.
> 
> I was going to try to do this by deleting the items from the Chroma db, but the IDs and such are all named long strings and I'm not sure how to delete a specific item.

you will have to make your own fork, write a function to add metadata and filter it with where.

**Comment by cachho** [comment]
@aaishikdutta thanks for picking this up.
