### ISSUE TITLE
[Feature Request] Collection name everywhere

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#261]
We have lots of users coming in, asking for ways to swap out embeddings for different use cases, while still keeping them. One simple methods are different collections, a feature supported by Chroma.

**We should make it that all configs allow to specify a collection name, that is then used by Chroma**

**Comment by deshraj** [comment]
Great idea @cachho. ❤️

**Comment by cachho** [comment]
> Great idea @cachho. ❤️

It's literally the feature you guys asked me to work on today.

**Comment by jonasiwnl** [comment]
Okay, understood.

> When do you think you have time to work on it?

I can start on this issue later today. However, if you would rather do it, just let me know and I can find another issue to work on.

**Comment by cachho** [comment]
> I would've done it differently. I would make a `set_collection` method on the App level, that sets an attribute. Upon setting it you create it if it doesn't exist already. Then you can easily reference that attribute using the `where` filter, whenever you use `add`, `chat` or `query` or in other places, if I'm forgetting anything.

I want to add that this method allows us to switch the collection at any time without initializing a new app. There should also be an option to set a collection at startup though, through InitConfig, that sets the same App attribute.

**Comment by jonasiwnl** [comment]
Okay, the collection can be switched at any time (without initializing a new App) and the collection can be specified on initialization with InitConfig.

> Then you can easily reference that attribute using the where filter, whenever you use add, chat or query

Should I still add the ability to query collections that aren't the current collection? For example,
```python3
app = App(InitConfig(collection_name="coll1"))

app.query(QueryConfig(collection_name="coll2")) # Queries collection 2
app.query() # Queries collection 1
```

**Comment by jonasiwnl** [comment]
Pull request opened (#310)
