### ISSUE TITLE
File names are inconsistent

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#267]
config folder contains file name in camel case convention
loaders contains file name in snake case.

we should formalize a style and then format / rename everything accordingly.

**Comment by cachho** [comment]
I think the convention of config is called PascalCase. As far as I know (the reason I did it) class names and the  names of the files containing just a class should be in CamelCase. So loaders should be adjusted.

Tests can't be adjusted because they need to be prefixed with test_

**Comment by rachittshah** [comment]
@taranjeet would you suggest a refactor of functions as well to improve test coverage?

Happy to pick this up!

**Comment by taranjeet** [comment]
I think we can skip refactoring functions in test coverage.
but we can pick up the rest.
lets first close how the file name, module name and class should be? 

like for module name we are using _, i think we should avoid that.

@rachittshah : do you want to take a lead in documenting everything?

**Comment by rachittshah** [comment]
@taranjeet yes, I'd love to lead the docs. I've been a doc writer for GSoD. Let me take notes and share it in the issue on the approach we can take.

**Comment by taranjeet** [comment]
Hi @rachittshah : checking if you are working on this?

**Comment by taranjeet** [comment]
from #321, by @deshraj 

```
Noticed that we have file names following the title casing (such as AppConfig.py) as well as snake casing (such as data_formatter.py) . We want to be more pythonic in this repository and follow snake case.
```

### Deliverables

- [ ] Change all title cased file names to snake case
- [ ] Update the code paths everywhere
- [ ] Update tests to make sure that they pass
- [ ] Update docs in the `/docs` folder

**Comment by Dev-Khant** [comment]
@taranjeet Can I pick this up?

**Comment by taranjeet** [comment]
Yes @Dev-Khant , please feel free to pick it up

**Comment by Dev-Khant** [comment]
@taranjeet @deshraj @cachho Is this needed to be done now so I can pick it up, or is kept on hold?

**Comment by Dev-Khant** [comment]
Closing this issue since all title cased file names are converted to snake case and docs have been updated.
