### ISSUE TITLE
[Bug] Incomplete read Error

### ISSUE THREAD

**Issue by dknamikaze** [embedchain/embedchain#269]
I am running on Python 3.11.3 on Windows OS. 

```python
from embedchain import OpenSourceApp

chat_bot= OpenSourceApp()

chat_bot.add_local("pdf_file", "C:\\ChatGPT\\test_embedchain\\content\\20060103.pdf")

chat_bot.query("Hi")
```

This is a simple test program and it throws out error - requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(877595012 bytes read, 1050851196 more expected)', IncompleteRead(877595012 bytes read, 1050851196 more expected))

I guessed that probably it is trying to download gpt4all and fail
<img width="952" alt="Screenshot 2023-07-15 Embedchain" src="https://github.com/embedchain/embedchain/assets/88419852/7aa2dc65-5336-452f-943b-1fa43dd98f51">
ed due to internet connection, so i ran again and it failed again with exact same error. My internet connection is stable. I am attaching the error screenshot below

**Comment by cachho** [comment]
I'm not on windows, can you test with an online PDF? Pdf loader is an online loader, not a local one.

However, you should be able to load local urls, but I'm not sure you can reference files like that. I think the syntax would be ``file://...` - open your file in chrome and you should see it.

**Comment by dknamikaze** [comment]
> I'm not on windows, can you test with an online PDF? Pdf loader is an online loader, not a local one.
> 
> However, you should be able to load local urls, but I'm not sure you can reference files like that. I think the syntax would be ``file://...` - open your file in chrome and you should see it.

@cachho tried after copying link after i opened the file with chrome. Attaching the screenshot
<img width="843" alt="Screenshot 2023-07-17 Embedchain E2" src="https://github.com/embedchain/embedchain/assets/88419852/b458c0cf-f215-49a2-8d33-5607c6a02412">

**Comment by cachho** [comment]
It clearly says that this is an issue with the filepath. We're going to have to test this on Windows.

**Comment by cachho** [comment]
In the meantime, I suggest you upload your PDF file somewhere on the internet, unless it's really secret. I think you can even use github for that.

**Comment by Dev-Khant** [comment]
Closing this issue now as the bug seems to have been fixed. Please feel free to open it again if there's still an issue.
