### ISSUE TITLE
sveltejs interface

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#28]
- wrap a @sveltejs interface around it and make an ai product.

- opened on behalf of Twitter user Patrick, [tweet link](https://twitter.com/patrickcurl/status/1671938640102998017)

**Comment by cachho** [comment]
We do have/are working on examples with nextjs. https://github.com/embedchain/qna-bot-template-js or https://github.com/embedchain/embedchain/pull/384 - I don't think the framework necessarily matters that much. I'm sure they can be improved and taken further, but I think this issue can be closed.
