### ISSUE TITLE
Make InitConfig DB agnostic

### ISSUE THREAD

**Issue by aaishikdutta** [embedchain/embedchain#297]
### 🚀 The feature

It's less of a feature and more of a refactor. Right now the configs are way too much aligned towards ChromaDB which is a good db for getting started with vector db's but not an ideal one for production. Hence users should be able to choose between different types of DBs. But the InitConfig is structured in such a way that the params are aligned towards chromadb. 

### Motivation, pitch

We need to make them DB agnostic. Also, the embedding function option is specific to chromadb and if kept default it will initialize a chromadb wrapper of an embedding model, which should not be the case.

**Comment by cachho** [comment]
Why do you say that? What param would not work with another database?

**Comment by cachho** [comment]
And I know we do have to standardize more and create methods in the `BaseVectorDb` class for standard behavior, that can be overwritten by the child classes, but I don't get the point with InitConfig.

**Comment by aaishikdutta** [comment]
> Why do you say that? What param would not work with another database?

Pinecone for example, doesn't have the port option. It has a host option but it is not something a free-tier user can explore hence I was not able to test it. Pinecone has a separate parameter it needs called environment. Also the embedding functions are a little different here than pinecone. Pinecone by default doesn't take in documents and internally embed it. These are some initial differences I found while trying to integrate pinecone.

**Comment by cachho** [comment]
I guess then the way to do it is to move that part to a `ChromaConfig`. And a respective `PineconeConfig`. We should still aim to reach a standardized `BaseVectorDb`, to abstract the functions.

**Comment by aaishikdutta** [comment]
We can discuss with a bigger forum before actually implementing it.

**Comment by Vasilije1990** [comment]
I've tried porting Pinecone, only to give up at a certain point. Saw same issues, and it seemed that a lot of code needs to be redone to support another db

**Comment by taranjeet** [comment]
hey @aaishikdutta , this is a good initiative. we should do it. Do you want to drive it end to end?

Let us plan all things before you start implementing. What all info/clarity/inputs do you think are needed before you start implementing this?
cc @deshraj @cachho

**Comment by aaishikdutta** [comment]
> Let us plan all things before you start implementing. What all info/clarity/inputs do you think are needed before you start implementing this? cc @deshraj @cachho
Sure, right now the biggest thing that come to mind is that unlike chroma, pinecone does neither accept nor provide embedding functions, which means we need to embed ourself and then pass around the vector. Haven't checked for Weaviate and Qdrant, but ideally the thing is to either detach embedding from DB or make it a plug and play part

**Comment by taranjeet** [comment]
We have taken step 1 in this direction by implementing a BaseVectorDb class and then adding support for elasticsearch.
The next thing that we can do to achieve more extensibility in BaseVectorDB is to add support for Pinecone and Weaviate. that way our base class will become mature and we will be able to support two more databases.

**Comment by taranjeet** [comment]
For pinecone we already have an issue: https://github.com/embedchain/embedchain/issues/39

**Comment by taranjeet** [comment]
for weaviate, created an issue https://github.com/embedchain/embedchain/issues/436

**Comment by taranjeet** [comment]
Closing this issue for now.
