### ISSUE TITLE
Docs: Missing Parts since Upgrade

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#299]
Since the update of the docs, we are missing a few points and chapters.

Here's what I caught so far:

* InitConfig: Server and Port
* QueryConfig: Number of documents

Please comment with anything you see that's missing.

**Comment by sahilyadav902** [comment]
- App Types: PersonOpenSourceApp

**Comment by taranjeet** [comment]
Added to #301 . Closing this one.
