### ISSUE TITLE
bug: Reset destroys app instance

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#300]
### 🐛 Describe the bug

When you use the `reset` method, the app instance is destroyed. It should be automatically reinitialized within the method, so that you can just keep using the app.

Not really a bug in the true sense, as it's not unexpected behavior.

**Comment by jonasiwnl** [comment]
PR opened (#319)

**Comment by taranjeet** [comment]
Closing this as the PR is merged.
thanks for opening the issue.
