### ISSUE TITLE
Update docs to make it easier to customize the app

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#301]
### 🚀 The feature

This is a running issue to update the doc and make it easy for everyone to learn and understand the framework.

- add details about .online
- how can we change the max_tokens?
- how can we use hugging face embeddings (https://github.com/embedchain/embedchain/issues/62)
- how can we use gpt-4 model (https://github.com/embedchain/embedchain/issues/73)

**Comment by taranjeet** [comment]
From #263 

i think this should be doable using config now. just that we need to update documentation where we can mention "gpt-4" as the model.

**Comment by taranjeet** [comment]
Update docs about:

InitConfig: Server and Port
QueryConfig: Number of documents

From: #299

**Comment by taranjeet** [comment]
Update docs about:

App Types: PersonOpenSourceApp

From #299

**Comment by Dev-Khant** [comment]
Closing this issue as documentation changes are done.
