### ISSUE TITLE
bug: the addconfig() does not work as it is being described as

### ISSUE THREAD

**Issue by YunchengLiang** [embedchain/embedchain#306]
### 🐛 Describe the bug

![image](https://github.com/embedchain/embedchain/assets/107207371/6c278137-69cc-4177-8d5b-a0f4af209743)
![image](https://github.com/embedchain/embedchain/assets/107207371/07cd39b2-8824-4ba9-aa60-5a5583de267d)
why would the number of chunks/embeddings not change no matter how i changed chunk_size? I made sure to clear the db and rerun the code everytime I want to use a different chunk_size for the target document

**Comment by YunchengLiang** [comment]
my bad, i tried it on a website with different chunk_size and it indeed yields different number of chunks.

**Comment by YunchengLiang** [comment]
I double confirmed with website as well and it generates the same number of chunks/embeddings no matter what i choose for the chunk_size , overlap and length_function

**Comment by cachho** [comment]
> I double confirmed with website as well and it generates the same number of chunks/embeddings no matter what i choose for the chunk_size , overlap and length_function

Are you on the latest version? We cleaned up the configuration, it works like this now: https://github.com/embedchain/embedchain/blob/0ea278f6336d92ae6f223e1222dc95f82dc7358a/docs/advanced/configuration.mdx#L28

**Comment by YunchengLiang** [comment]
> > I double confirmed with website as well and it generates the same number of chunks/embeddings no matter what i choose for the chunk_size , overlap and length_function
> 
> Are you on the latest version? We cleaned up the configuration, it works like this now:
> 
> https://github.com/embedchain/embedchain/blob/0ea278f6336d92ae6f223e1222dc95f82dc7358a/docs/advanced/configuration.mdx#L28

![image](https://github.com/embedchain/embedchain/assets/107207371/27711dd7-b18d-4d06-a806-c50a335d7dcc)
Thank you for the reply cachho, yes, I reinstalled the embedchain and it was the lastest version.
And I also just tried using "chunker=chunker_config" like the screenshot below but it still gives the same number of chunks.
![image](https://github.com/embedchain/embedchain/assets/107207371/089b8031-cc29-4625-97a9-b37138143235)
![image](https://github.com/embedchain/embedchain/assets/107207371/d84037ee-b5a5-4821-90f7-b16d9aa2a99d)

Could you please also try this on any one of your document and see if that yields the same number of chunks?
Thank you very much.

**Comment by cachho** [comment]
Definitely worrying, I hope I can look into this tomorrow.

**Comment by cachho** [comment]
I can confirm:

```
from embedchain import App
from embedchain.config import AddConfig, ChunkerConfig

app = App()
config = AddConfig(chunker=ChunkerConfig(chunk_size=10000))
app.add_local("text", "lorem ipsum dolor sit amet, consectetur adipiscing el")
# Successfully saved lorem ipsum dolor sit amet, consectetur adipiscing el. New chunks count: 1

config = AddConfig(chunker=ChunkerConfig(chunk_size=1))
app.add_local("text", "lorem ipsum dolor sit amet, consectetur adipiscing el.")
# Successfully saved lorem ipsum dolor sit amet, consectetur adipiscing el.. New chunks count: 1
```

**Comment by cachho** [comment]
It would've helped to actually use the config.

```python
from embedchain import App
from embedchain.config import AddConfig, AppConfig, ChunkerConfig

app = App(config=AppConfig(log_level="DEBUG"))
app.reset()
app = App(config=AppConfig(log_level="DEBUG"))

config = AddConfig(chunker=ChunkerConfig(chunk_size=10000))
app.add_local("text", "lorem ipsum dolor sit amet, consectetur adipiscing el", config=config)
# 2023-07-19 11:15:03,938 [openai] [DEBUG] api_version=None data='{"input": ["lorem ipsum dolor sit amet, consectetur adipiscing el"], "encoding_format": "base64"}' message='Post details'
# Successfully saved lorem ipsum dolor sit amet, consectetur adipiscing el. New chunks count: 1

config = AddConfig(chunker=ChunkerConfig(chunk_size=1))
app.add_local("text", "lorem ipsum dolor sit amet, consectetur adipiscing el.", config=config)
#2023-07-19 11:15:04,260 [openai] [DEBUG] api_version=None data='{"input": ["l", "o", "r", "e", "m", " ", "i", "p", "s", "u", "d", "t", "a", ",", "c", "n", "g", "."], "encoding_format": "base64"}' message='Post details'
# Successfully saved lorem ipsum dolor sit amet, consectetur adipiscing el.. New chunks count: 18
```

Please try with my example. I can't reproduce your bug anymore.

**Comment by cachho** [comment]
what's the reason you are using a different length_function?

**Comment by YunchengLiang** [comment]
> what's the reason you are using a different length_function?

Hi cachho, I tried using the same length_function(len) and only change the chunk_size, it yielded the same number of chunks/embeddings.       
The reason that I am using a different length_function is because the original default len function count the number of characters in each chunk and use that as the length of each chunk (so if chunk_size is 1000, each chunk we get should be less than 1000 characters), however for default open-souce embedding we are using which is the [all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2), it says any input longer than 256 "tokens" will be truncated, so I created this customized function to count number of tokens and use chunk_size to set the upperbound for each chunk in terms of tokens number.
![image](https://github.com/embedchain/embedchain/assets/107207371/9e223dc5-4c4b-43ef-9da3-8114cb3824ad)

**Comment by YunchengLiang** [comment]
> I can't reproduce your bug anymore.
Hi cachho, I am instead using "opensourceapp" and "add" like the code below

chat_bot = OpenSourceApp()
pdf_url = 'https://www.rogers.com/cms/pdf/en/Consumer_SUG_V20.pdf'
config = AddConfig(chunker=ChunkerConfig(chunk_size=1, chunk_overlap=0, length_function=len))
chat_bot.add('pdf_file', pdf_url, config=config)

Then i encountered this following error...
TypeError: langchain.text_splitter.RecursiveCharacterTextSplitter() argument after ** must be a mapping, not ChunkerConfig
