### ISSUE TITLE
feature request: pass anything as metadata

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#317]
### 🚀 The feature

You should be able to pass anything as metadata, through the input of a dict.

This applies to the `add` method mostly. This should be added to `AddConfig`.

But then you should also be able to filter the query with `where` from the `QueryConfig`.

### Motivation, pitch

Let's say you want to evaluate URLs, but one site is JS based so you use selenium to get the text and then load add it with the `text` datatype. Now it does not have the source metadata tag.

**Comment by aaishikdutta** [comment]
can you please provide detail? Also, I thought we had metadata parameter in add method that can take in a dict and it was added to the metadata generated by loaders. I guess it was this PR #253

**Comment by cachho** [comment]
> hi @cachho, can you please provide detail? Also, I thought we had metadata parameter in add method that can take in a dict and it was added to the metadata generated by loaders. I guess it was this PR #253

you're right, looks like we already have this.
