### ISSUE TITLE
[ux improvement]: Make file names consistent across the project

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#321]
### 🚀 The feature

Noticed that we have file names following the title casing (such as `AppConfig.py`) as well as snake casing (such as `data_formatter.py`) . We want to be more pythonic in this repository and follow snake case. 

### Deliverables

- [ ] Change all title cased file names to snake case
- [ ] Update the code paths everywhere
- [ ] Update tests to make sure that they pass
- [ ] Update docs in the `/docs` folder

### Motivation, pitch

Motivation is to keep the project file names consistent across the repo.

**Comment by taranjeet** [comment]
@rachittshah: Do you want to take this up? You commented about working on #267 , which is related to this. Let me know.

**Comment by rachittshah** [comment]
@taranjeet would you recommend picking this over #267 ?

**Comment by taranjeet** [comment]
Hey @rachittshah , sure you can start with this.

**Comment by taranjeet** [comment]
Closing this issue. Tracking everything in #267
