### ISSUE TITLE
[ux improvement]: remove `dry_run` attribute and add this functionality as a kwargs

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#322]
### 🚀 The feature

Currently, we expose `dry_run` as an attribute of the App object and instead we want to add it as a kwarg in the `.query()` function.

### Deliverables
- [ ]  Remove `dry_run` attribute and add this functionality as a kwargs
    - Example: `.query(input, dry_run=True)`
    - Default value for `dry_run` will be `False`
- [ ] Update documentation here https://docs.embedchain.ai/advanced/testing#dry-run

### Motivation, pitch

We only want to expose certain functions for the bots that will be built using embedchain. Attributes like `dry_run` and `count` make little sense to be exposed for the embedchain bots. We will instead keep these as kwards and methods respectively. 

It is understood that these might be the breaking changes but it is necessary to make the project successful in the longer run by making these design decisions early on.

**Comment by aaishikdutta** [comment]
Raised #329 @deshraj
