### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'embedchain.apps'

### ISSUE THREAD

**Issue by vpinigin** [embedchain/embedchain#334]
### 🐛 Describe the bug

It seems that something was broken during yesterday update

```
from embedchain import OpenSourceApp
app = OpenSourceApp()
```

`ModuleNotFoundError: No module named 'embedchain.apps'`

**Comment by vpinigin** [comment]
I used it from pip in google colab with --upgrade flag

**Comment by cachho** [comment]
![image](https://github.com/embedchain/embedchain/assets/14180064/b557899f-d2a1-498b-9a1a-f7e74dc3f700)

@taranjeet looks like in the pip distribution, for some reason Apps is capitalized.

**Comment by Apicio** [comment]
Any solution for this? I get the same error :(

**Comment by taranjeet** [comment]
Hey, I have figured the fix. Publishing package soon.

**Comment by taranjeet** [comment]
Hey @Apicio @vpinigin @cachho : just fixed this. Please try version 0.0.27
https://pypi.org/project/embedchain/0.0.27/

Let me know if it doesnt work.
