### ISSUE TITLE
[Thoughts] Struggling with dependencies

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#335]
### 🐛 Describe the bug

Since the latest update, I've been struggling with dependencies.

**We should generally question, whether we want to have all LLMs we use as a dependency. Right now embedchain is forcing me to install GPT4ALL, replicate, sentence transformers and openai, even if I'm using only one of them.**

Especially in a dockerized production environment, I don't need that. 

# Proposal

In my recent PRs, I used the following snippet. 

```python
try:
    from gpt4all import GPT4All
except ModuleNotFoundError:
    raise ValueError(
        "The GPT4All python package is not installed. Please install it with `pip install GPT4All`"
    ) from None
```

with this approach, users see an error message and can install the dependencies they need, while not installing everything they don't need

Question: If we want to include all llms in the deps, because it means users have to type in one less command, is there a feasible way to publish a "light" package where the user installs the llm dependencies themself?

# My problem and solution

This is the `requirements.txt` that does not work.
```
Flask==2.1.3
Flask-Cors==3.0.8
requests==2.28.0
gunicorn==20.1.0
Flask-Caching==2.0.2 
redis==4.4.2
supabase==1.0.3
embedchain==0.0.26
```

The only thing I changed was updating to the newest embedchain version.

I fixed the problem by **removing** the following dependencies from embedchain's `setup.py`.

```
"gpt4all",
 "sentence_transformers",
"replicate==0.9.0",
"duckduckgo-search==3.8.4",
```
I kept `openai` because that's what I use, but you could remove that too.

Then I built my own package with `python3 setup.py sdist` and put the local file in `requirements.txt`.

**Comment by cachho** [comment]
Trying to let pip figure out all these dependencies took me:

![image](https://github.com/embedchain/embedchain/assets/14180064/e6dc19c1-807b-43dc-9d26-a241a15001ec)

**Comment by cachho** [comment]
This is the error btw.

```
#0 405.7 The conflict is caused by:
#0 405.7     supabase 1.0.3 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     gotrue 1.0.1 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     postgrest 0.10.6 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     storage3 0.5.2 depends on httpx<0.24 and >=0.23
#0 405.7     supafunc 0.2.2 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     httpx[brotli,http2,socks] 0.24.1 depends on httpx 0.24.1 (from https://files.pythonhosted.org/packages/ec/91/e41f64f03d2a13aee7e8c819d82ee3aa7cdc484d18c0ae859742597d5aa0/httpx-0.24.1-py3-none-any.whl (from https://pypi.org/simple/httpx/) (requires-python:>=3.7))
#0 405.7 
#0 405.7 To fix this you could try to:
#0 405.7 1. loosen the range of package versions you've specified
#0 405.7 2. remove package versions to allow pip attempt to solve the dependency conflict
#0 405.7 
#0 405.7 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by cachho** [comment]
To make it clear, this isn't really an embedchain issue and could also be blamed on supabase, but if we keep our dependency footprint smaller we will run into fewer issues.

**Comment by Vasilije1990** [comment]
I had the same issue with gpt4all. I support streamlining this. Also, running chromadb in docker was a pain
