### ISSUE TITLE
docs: documentation needs modification

### ISSUE THREAD

**Issue by YunchengLiang** [embedchain/embedchain#340]
### 🐛 Describe the bug

on this page https://docs.embedchain.ai/advanced/configuration    
the demo here needs to be modified:     

```python
# Example: define your own chunker config for `youtube_video`
chunker_config = ChunkerConfig(chunk_size=1000, chunk_overlap=100, length_function=len)
naval_chat_bot.add("youtube_video", "https://www.youtube.com/watch?v=3qHkcs3kG44", AddConfig(chunker=chunker_config))   `
```

it should be the following instead, else will not work as intended, thank you!   
```python
naval_chat_bot.add("youtube_video", "https://www.youtube.com/watch?v=3qHkcs3kG44", config=AddConfig(chunker=chunker_config))   
```

**Comment by cachho** [comment]
Yes, that's better, but it goes for the whole file. You can open a PR if you want.

**Comment by YunchengLiang** [comment]
> Yes, that's better, but it goes for the whole file. You can open a PR if you want.

thank you, i will open a pr then!
