### ISSUE TITLE
TypeError: 'NoneType' object is not a mapping

### ISSUE THREAD

**Issue by Sarthakpujari** [embedchain/embedchain#347]
### 🐛 Describe the bug

Hi, while running the demo colab notebook, I getting this error - 
<img width="918" alt="image" src="https://github.com/embedchain/embedchain/assets/54023844/2375b9ce-d172-4f40-9bda-5af682504864">

Its unusual since I have used it earlier, but never faced this issue. Kindly look into this.

**Comment by taranjeet** [comment]
Hey @Sarthakpujari , thanks for reporting. Found the bug.
Fixing it

**Comment by taranjeet** [comment]
Hey @Sarthakpujari , just fixed the package.
https://pypi.org/project/embedchain/0.0.29/

Can you try upgrading to version 0.0.29?

**Comment by Sarthakpujari** [comment]
yeah, it's fixed. Thanks!
