### ISSUE TITLE
bug: unsatisfying results with `youtube_video` format

### ISSUE THREAD

**Issue by funkytaco** [embedchain/embedchain#359]
### 🚀 The feature

I've tried `llm_bot.add("youtube_video", "https://www.youtube.com/watch?v=48h57PspBec")`

And the AI acted like it knew nothing about the videos when I queried. I'm not sure if I need to do anything else. I made sure the youtube-transcript-api was installed.

### Motivation, pitch

What does youtube_video do?

**Comment by aaishikdutta** [comment]
Hey @funkytaco can you check the query method with dry_run attribute as true and see what result is it printing?

**Comment by funkytaco** [comment]
#stripping out the flask API stuff, but this is basically it

from flask import Flask, request, jsonify
from flask_cors import CORS
from embedchain import App
from dotenv import load_dotenv
from urllib.parse import urlparse
import os

load_dotenv()

app = Flask(__name__)
CORS(app)

llm_bot = App()
 file_name = 'youtube_video'
file_url = 'https://www.youtube.com/watch?v=48h57PspBec'
    llm_bot.add(file_name, file_url)
    
    response = llm_bot.query(data['input'],dry_run=True)
    return jsonify({
        "role": "assistant",
        "content": response
    })
    
    Response:
    
    `{
    "content": "\n  Use the following pieces of context to answer the query at the end.\n  If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\n  \n\n  Query: what yachts are in the doc?\n\n  Helpful Answer:\n",
    "role": "assistant"
}`

**Comment by aaishikdutta** [comment]
Not sure but by any chance did you delete the db folder that got created. I know it sounds silly but that's the only way I could recreate the exact dry_run output

**Comment by cachho** [comment]
closing this, please reopen if you find out how to make this reproducible so we can help you.
