### ISSUE TITLE
In Citation section, title misses the "d"

### ISSUE THREAD

**Issue by alessandropanzieri** [embedchain/embedchain#366]
### 🐛 Describe the bug

I noticed that in Citation section, title misses the "d": is "EmbedChain", not "EmbeChain"...
I think it's not so good to be cited with a wrong title ahahaha :)

**Comment by cachho** [comment]
Good catch, do you want to open a PR?

**Comment by alessandropanzieri** [comment]
I've just make a PR👍

**Comment by taranjeet** [comment]
thanks @alessandropanzieri . 
Closed
https://github.com/embedchain/embedchain/pull/369
