### ISSUE TITLE
feature request: youtube video in other language

### ISSUE THREAD

**Issue by sinecode59** [embedchain/embedchain#385]
### 🚀 The feature

Being able to use the "youtube_video" format in other language like for example 'French'. 
Today is not working when you put the link of a french youtube video.
Maybe there is a way to define the target language for youtube audio transcription (using Langchain behind) but I've not found any mention about this in the documentation. 

### Motivation, pitch

Be able to use the 'youtube_video' option with youtube video links not in English (by default)

**Comment by cachho** [comment]
So you want it to be in a language that's not actually spoken in the video, you want to be able to choose from one of the available subtitles. Do I understand that correctly?

**Comment by avri-schneider** [comment]
@cachho currently only `en` language is supported. `YoutubeLoader.from_youtube_url()` allows passing additional parameters (e.g., `language`), which currently `YoutubeVideoLoader.load_data()` doesn't pass, thus [.from_youtube_url()](https://github.com/langchain-ai/langchain/blob/733367b7954b9bb6c89ba150154e4f942a337a06/libs/community/langchain_community/document_loaders/youtube.py#L217-L220) defaults to `en`.

**Comment by deshraj** [comment]
Hey @avri-schneider, thanks for reporting the issue. We would appreciate if you can put up a fix for this. Thanks!

**Comment by avri-schneider** [comment]
Hey @deshraj [the fix](https://github.com/embedchain/embedchain/pull/774) is there (provided by [Akemid](https://github.com/Akemid)), just needs to be merged, but [stalled](https://github.com/embedchain/embedchain/pull/774#issuecomment-1867537387) due to conflics :-/

**Comment by deshraj** [comment]
Ah nice, thanks for bringing to my attention. Will review and merge shortly.
