### ISSUE TITLE
Add support for Pinecone as vector database

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#39]
- Currently, is it possible to use embedchain with pinecone? If not, will it be possible in the future?
- this issue is opened on behalf of discord user Hector, [message link](https://discord.com/channels/1121119078191480945/1121119078858358846/1121781306708213820)

**Comment by cachho** [comment]
weaviate is another name that comes to mind. it's actually open source.

**Comment by jacob-dietle** [comment]
I'm working on a PineconeDB class based on the BaseVectorDB class currently. I initially thought it would pretty straight forward to map pinecone logic to  the `_get_or_create_db`  and `_get_or_create_collection` methods but it seems like collections in Pinecone and Chroma differ slightly so I am still trying to figure that out. I don't have a lot of experience with vector dbs so I would appreciate some clarity on the differences between how Pinecone and Chroma define collections and indexes if anyone has experience with both of these tools.

**Comment by taranjeet** [comment]
https://twitter.com/tricalt/status/1676999694096924686
