### ISSUE TITLE
feature request: Multiple "Brains" like Quivr.

### ISSUE THREAD

**Issue by funkytaco** [embedchain/embedchain#396]
### 🚀 The feature

The ability to silo documents to a namespace. Quivr calls this a brain. 

### Motivation, pitch

To keep documentation silod. This may later allow role-base access control to data silos. 

### Additional context

- Upload Topic A documents to a namespace called Topic A.
- Upload Topic B documents to a namespace called Topic B.
- AI should only have context for the current namespace. 
- Each Brain can use a different GPT key.
- Each Brain can use a different temperature.
- Each Brain can use a different token count.
- Eventually, RBAC could be added to allow multi-user with different privileges.

**Comment by Dev-Khant** [comment]
Closing this issue as it has been fixed.
