### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#40]
- need to setup tests so that contributing to the repo becomes easier and faster

**Comment by amjadraza** [comment]
I can help on this

**Comment by taranjeet** [comment]
Hey @amjadraza , thats so great. Please feel free to take a lead on this. Let me know if anything is needed.

**Comment by amjadraza** [comment]
@taranjeet I have added the same task in #72. See if we can merge this issue with #72

**Comment by taranjeet** [comment]
Lets track test in this issue and for others lets track in #72

**Comment by taranjeet** [comment]
Closing this issue, as we already have tests now.
