### ISSUE TITLE
bug: open source app instantiates chroma somewhere

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#415]
### 🐛 Describe the bug

I just started an open source app and it printed

`ERROR:chromadb.telemetry.posthog:Failed to send telemetry event client_start: module 'chromadb' has no attribute 'get_settings'`

so chroma must be initialized somewhere. We have to find and eliminate this.

**Comment by taranjeet** [comment]
@cachho : I tried the following code snippet. It worked.
```
In [1]: from embedchain import OpenSourceApp

In [2]: app = OpenSourceApp()

```

Closing this issue. Feel free to reopen if you think I am missing something or share code snippet.

**Comment by cachho** [comment]
My mistake, I forgot that the open source model still uses Chroma, as a database, not as an embedding function.
