### ISSUE TITLE
feature request: txt loader

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#417]
### 🚀 The feature

implement #89 the right way.

Add a loader to embed local files.

### Motivation, pitch

This is a simple function that should be provided.

### Alternatives

Alternatively

```python
with open(path) as f:
    for line in f.read_lines():
        app.add("text", line)
```

isn't a lot of code.

This gives you control whether you want to read the whole file at once, or like I did, line by line.

### Additional context

* I think `txt` is to close to `text`, `file` would be more descriptive
* with that being said, file implies that all files could be read, when it's only text. So what do we call it?
* as mentioned, how do we read the whole file at once or line by line, depending on the type of document one or the other might be required.

**Comment by Dev-Khant** [comment]
I can pick this up.

**Comment by taranjeet** [comment]
@deshraj see if we need this?
