### ISSUE TITLE
Add chat endpoint in the api server example

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#433]
### 🚀 The feature

- add chat endpoint in the api server

### Motivation, pitch

this completes the entire api server for a user and they can know try both chat and query

**Comment by pcha07** [comment]
hi could you please provide more information i am interested in this issue and would like to contribute.

**Comment by taranjeet** [comment]
Sure, we have added an example of api server in the repo here: https://github.com/embedchain/embedchain/tree/main/examples/api_server

It has query endpoint. We need to expose chat endpoint in the api.

**Comment by taranjeet** [comment]
@pcha07 : added details in the above comment. let me know if you have any doubt.

**Comment by BattiniSandeep** [comment]
Is this issue completed?

**Comment by PatelKeviin** [comment]
I believe this should be closed as I can see a `chat` endpoint being exposed in the `api_server.py` example file. :)

<img width="773" alt="image" src="https://github.com/embedchain/embedchain/assets/42174390/70c68472-de9e-4ac2-b4d3-2d39fe4c5093">

**Comment by sandrasgg** [comment]
Hey, is this issue still open? I'd like to contribute but it looks as if it has already been done according to the last message

**Comment by deshraj** [comment]
Yes, this is already fixed. Thanks for the reminder. Will close this issue now.
