### ISSUE TITLE
Set telemetry flag as a top level attribute on Emebdchain class

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#444]
### 🚀 The feature

Right now we have a telemetry flag called `collect_metrics`. It is available as a flag in the config.
We need to set it as a top level flag

```
app.collect_metrics = False/True
```

### Motivation, pitch

this enables anyone to easily toggle on/off the metrics

**Comment by Dev-Khant** [comment]
@taranjeet Do we also want to keep in config or remove from there?

**Comment by taranjeet** [comment]
@Dev-Khant : it will be there in both config and top level attribute.

**Comment by Dev-Khant** [comment]
Yes, I understood it. Thanks
