### ISSUE TITLE
chore: update default embedding model

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#463]
### 🐛 Describe the bug

We currently use `ada`, which will be deprecated Jan 4th, 2024.

**Comment by Dev-Khant** [comment]
`text-embedding-ada-002` is used. So where exactly can I find the issue then?
![image](https://github.com/embedchain/embedchain/assets/57898986/dda3ba8f-f94b-46c0-9154-e0eb1cafbc63)
