### ISSUE TITLE
Add contributor graph or widget in readme

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#485]
### 🚀 The feature

- add a contributor graph or widget in the readme like vuejs https://github.com/vuejs/vue

### Motivation, pitch

We have got some really good contributions from contributors worldwide, so want to make it more evident on the readme.

**Comment by josephchancey** [comment]
Pull request open for this issue. If it is preferred to not use contrib.rocks as a solution then I can find alternatives. Thank you for your time! 😄 

https://github.com/embedchain/embedchain/pull/495

**Comment by taranjeet** [comment]
closing this as its addressed.
