### ISSUE TITLE
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

### ISSUE THREAD

**Issue by silvacarl2** [embedchain/embedchain#506]
### 🐛 Describe the bug

when trying to pip install in google colab, get this error message:

ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by Viachek** [comment]
Yes, I have the same error when trying to test in Colab

**Comment by deshraj** [comment]
Yes, I was able to reproduce this issue on colab. You can resolve the issue by doing something like this on colab notebook:

```bash
!pip3 install --ignore-installed embedchain
```

Example notebook I just created: 
 https://colab.research.google.com/drive/1_RQ7gZkjR68ZRZhod5RkmWoRTkkX1udp#scrollTo=izsOEvX_ZpAh

**Comment by deshraj** [comment]
You can ignore the warning I believe. This seems specific to the google colab and I don't see this issue on my mac. 

Regarding rate limiting, seems like you are using your openai api key too often. Might want to wait for sometime before retrying.
