### ISSUE TITLE
Fine tune tone for the answer

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#52]
- Wondering if it is possible to fine-tune the tone the AI replying to me? such as if I provided the dialogue of Sherlock Holmes, could it reply me with the tone that Sherlock talks? Ty!
- this issue is opened on behalf of twitter user ring_hyacinth, [tweet](https://twitter.com/ring_hyacinth/status/1672623784237613057)

**Comment by batmanscode** [comment]
Maybe an option to customize the prompt would be a general solution

**Comment by cachho** [comment]
Person bot is a thing now. Closing this issue. #182
