### ISSUE TITLE
Pre-commit Issue 

### ISSUE THREAD

**Issue by rajveer43** [embedchain/embedchain#521]
![image](https://github.com/embedchain/embedchain/assets/64583161/0adf13da-b261-466d-93b5-9dd4df3960b4)

I was trying to commit to create a PR. but without changes to code. I added docstrings with examples but it is faling to push due to this error any idea?

**Comment by cachho** [comment]
Hey, I'm facing the same issue. I thought I'm the only one on the team. I did a clean install of the venv multiple times. No idea why. 4 tests are always failing. This is only local though, in the github action it works.

If you find out how to fix this, please let me know. You should try to open a ticket on the ChromaDB github.

Until then, you can only ignore it.

**Comment by cachho** [comment]
I don't understand @rajveer43

**Comment by taranjeet** [comment]
closing this issue. Feel free to re-open if it still occurs.
