### ISSUE TITLE
Feature request: Slack channel/instance as a data source

### ISSUE THREAD

**Issue by itamargo** [embedchain/embedchain#524]
### 🚀 The feature

Provide the ability to point the bot to an entire Slack instance or a specific Slack channel as a data source

### Motivation, pitch

As much as we'd like it to not be true, in many organizations, Slack unintentionally ends up becoming the system of record for some knowledge. Being able to include it as a data source for the bot will unlock the creation of richer, more knowledgable experience

**Comment by Dev-Khant** [comment]
`Slack` as data source has been added https://docs.embedchain.ai/components/data-sources/slack
