### ISSUE TITLE
Feature request: Google drive folder/instance as a data source

### ISSUE THREAD

**Issue by itamargo** [embedchain/embedchain#525]
### 🚀 The feature

Rather than adding one document at a time, enable the bot to ingest an entire google folder or directory structure

### Motivation, pitch

often times, the knowledge on which you want to train the bot is already curated, Pointing it to that repository rather than having to manually enter the URL of each and every file will save a lot of setup time and as well as make supporting more dynamic knowledge bases easier - you don't have to have a preconceived notion of how the knowledge is divided and across which files.

**Comment by cefege** [comment]
Yes, that would be very usefull.

**Comment by vishutupili** [comment]
Hi, I would like to work on this issue. Could you assign it to me?

**Comment by JoeSL** [comment]
Hello, if no one is working on it I would love to!

**Comment by taranjeet** [comment]
hey @JoeSL , just assigned it to you.
