### ISSUE TITLE
Error on Colab

### ISSUE THREAD

**Issue by mehulgit** [embedchain/embedchain#538]
### 🐛 Describe the bug

Opened the demo on colab and 'pip install  --upgrade embedchain' throws the following error: ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by ranjancse26** [comment]
Same error - ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by ArnavK-09** [comment]
### +1 Same Error...

**Comment by taranjeet** [comment]
Hey, can you please run the following

```
!pip3 install --ignore-installed embedchain
```

Please check https://github.com/embedchain/embedchain/issues/506 for context.

**Comment by taranjeet** [comment]
Closing this issue since no comments since 2 weeks.
Please feel free to re-open if the issue still exists.
