### ISSUE TITLE
Hoping to support custom openai base_url.

### ISSUE THREAD

**Issue by Veinsvx** [embedchain/embedchain#56]
I hope for support for a custom base_url. This is because the original base_url from OpenAI is sometimes not directly accessible from my region.

**Comment by guaguaguaxia** [comment]
proxy = "http://127.0.0.1:7890"
os.environ["http_proxy"] = proxy
os.environ["https_proxy"] = proxy

fix those code before your main code

**Comment by Veinsvx** [comment]
ok，thanks

**Comment by sandangel** [comment]
Hi, I have the embed model running on different service, not the same with llm base url. Is it possible to add base url for each?
