### ISSUE TITLE
Self-hosted ChromaDB: cannot import name 'ChromaDbConfig' from 'embedchain.config'

### ISSUE THREAD

**Issue by denisj** [embedchain/embedchain#572]
### 🐛 Describe the bug

```python
import os
from embedchain import CustomApp
from embedchain.config import CustomAppConfig, AddConfig, ChunkerConfig, ChromaDbConfig
```

I get 
```
ImportError: cannot import name 'ChromaDbConfig' from 'embedchain.config'
```

I'm trying to connect to my ChromaDB
```
chroma_config = ChromaDbConfig(
  collection_name="default_collection",
  dir="db",
  host="localhost",
  port="8000",
)
```

Is it possible to use our own external ChromaDB?

**Comment by cachho** [comment]
Hey, did you install from pypi or is this from the main branch?

**Comment by cachho** [comment]
The docs are for the main branch which is a little bit ahead of pypi right now. Pypi doesn't have a chromadb config.

**Comment by cachho** [comment]
Closing this as I think it's been fixed by the new release/sync. Please reopen if you need more help.
