### ISSUE TITLE
Python CI/CD should not run for changes in embedchain-js folder

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#577]
### 🚀 The feature

We merged [embedchainjs](https://github.com/embedchain/embedchainjs) into this repo.
CI/CD of python repo should not run for changes in embedchain-js folder.

### Motivation, pitch

better CI

**Comment by dtee1** [comment]
Interested

**Comment by cachho** [comment]
> Interested

go ahead.

**Comment by Dev-Khant** [comment]
Closing this issue as EmbedchainJS is no longer available.
