### ISSUE TITLE
Javascript / Nodejs version of EmbedChain?

### ISSUE THREAD

**Issue by davidoort** [embedchain/embedchain#58]
Hi, is there are JS version of EmbedChain (similar to what was done with LangChainJS) in the works?

Thanks for building this!
David

**Comment by davidoort** [comment]
All the building blocks of the EmbedChain tech stack have JS versions so I assume it shouldn't be too hard

**Comment by taranjeet** [comment]
Hi, I have started a repo for this https://github.com/embedchain/embedchainjs

Will be publishing the package soon.

You can star or watch a repo to stay updated.

**Comment by davidoort** [comment]
Awesome, will keep an eye out! Is soon in the order of days, weeks or months?

**Comment by taranjeet** [comment]
@davidoort 

JS Package is now live:

https://github.com/embedchain/embedchainjs

Closing this issues.
