### ISSUE TITLE
feature request: automatically chunk .csv files

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#586]
### 🚀 The feature

Chunk csvs on a embedchain package level so that we don't run into rate limits.

### Motivation, pitch

This shouldn't be too hard since we submit each line with headers anyways.

**Comment by Dev-Khant** [comment]
@cachho I would like to pick this up. Could please give more clarity on what and where is the issue?

**Comment by cachho** [comment]
@Dev-Khant actually, this isn't going to work as I thought, because we already create a separate document for each line in the .csv. So we already have chunking.

The problem lies with Chroma, it's trying to submit them all at once. So this is a problem of #429.

I guess I can close this because chunking in the loader is alrady established, it just has to be added in the add function now.
