### ISSUE TITLE
JSON format is not supported

### ISSUE THREAD

**Issue by abhijitmaji27** [embedchain/embedchain#588]
### 🚀 The feature

ValueError: ("Invalid data_type: 'json'.", "Please use one of the following: ['youtube_video', 'pdf_file', 'web_page', 'sitemap', 'docx', 'docs_site', 'text', 'qna_pair', 'notion', 'csv']")

### Motivation, pitch

Please add the new type JSON

**Comment by cachho** [comment]
Hey, you aren't the first to request this, so we might eventually do it. But I recommend you take the time and write your own parser, because each json data structure is different and you know better what you want to do with yours than we could ever. A "one size fits all" solution is almost impossible for us to create.

You can schedule a meeting with our founder through the link in this repo's readme, or you can share a sample of your csv here and we can help you.

**Comment by abhijitmaji27** [comment]
It cannot read csv files correctly. it shows the following error UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3226: character maps to <undefined>

**Comment by cachho** [comment]
I think that means we would have to write a encoding detector. I don't think that's a small task, and it's not requested by many people, so don't expect us to do it any time soon. We're also going to have to figure out if the embedder and llm can even work with these chars, if there is any benefit to this.

What you can do in the meantime is programmatically replace non-unicode characters. That's what we might do first as well.

**Comment by abhijitmaji27** [comment]
{
        "lowestResellPrice": {
            "stockX": 236,
            "flightClub": 224,
            "goat": 224
        },
        "imageLinks": [],
        "_id": "64ff1a8c4dcc9a2e6d02f61f",
        "shoeName": "Jordan 4 Retro Red Cement",
        "brand": "Jordan",
        "silhoutte": "Jordan 4 Retro",
        "styleID": "DH6927-161",
        "make": "Jordan 4 Retro",
        "colorway": "White/Fire Red/Black/Neutral Grey",
        "retailPrice": 210,
        "thumbnail": "https://images.stockx.com/images/Air-Jordan-4-Retro-Red-Cement-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1692111483",
        "releaseDate": "2023-09-09",
        "description": "The Air Jordan 4 Retro ‘Red Cement’ is a midtop delivered in a color scheme reminiscent of the original ‘White Cement’ model, with a white leather upper with black accents on the lining and molded eyelets. Fire Red accents with black speckling adorn the support wings, heel tab and midsole. The heel displays an embossed Jumpman logo, and a second Jumpman appears on the tongue tag. The herringbone-patterned rubber outsole provides excellent grip on the court.",
        "urlKey": "air-jordan-4-retro-red-cement",
        "resellLinks": {
            "stockX": "https://stockx.com/air-jordan-4-retro-red-cement",
            "flightClub": "https://www.flightclub.com/air-jordan-4-retro-red-cement-dh6927-161",
            "goat": "http://www.goat.com/sneakers/air-jordan-4-retro-red-cement-dh6927-161"
        },
        "goatProductId": 1200361
    }

I am using that json so how can I resolve the non-unicode characters issue, can you please guide me here.

**Comment by cachho** [comment]
```python
import re
import json

def clean_json_string(json_string):
    # Remove non-Unicode characters
    cleaned_string = re.sub(r'[^\x00-\x7F]+', '', json_string)
    return cleaned_string

# Read the JSON from a file
with open("data.json", "r", encoding="utf-8") as file:
    json_str = file.read()

cleaned_json_str = clean_json_string(json_str)

# Parse the cleaned JSON string to a Python dictionary
data = json.loads(cleaned_json_str)
print(data)
```

just replace the file name and then parse `data` and pass the values to embedchain.

**Comment by abhijitmaji27** [comment]
Thanks. It resolved the issue.
