### ISSUE TITLE
dont print the entire text when data type is text

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#602]
### 🐛 Describe the bug

When we are adding a data type "text", the entire text gets printed due to the below statement. 

we can either skip printing text altogether or print part of it.

print(f"All data from {src} already exists in the database.")

**Comment by dtee1** [comment]
Could this be assigned to me?

**Comment by taranjeet** [comment]
Hey @dtee1 welcome to embedchain.
Yeah sure. Just assigned.
