### ISSUE TITLE
feature request: `allow_reset` as a constructor argument for `ChromaDbConfig`

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#608]
### 🚀 The feature

Currently we throw 
```
ValueError: For safety reasons, resetting is disabled.Please enable it by including `chromadb_settings={"allow_reset": True}` in your ChromaDbConfig`.
```

It's debatable whether we need this safety mechanism at all.

But either way, allow_reset should be directly configurable under ChromaDbConfig, without the need to pass it as a dict in the "advanced settings".

So the task is to make this accessible from the ChromaDbConfig constructor.

This 

```python
app = App(chromadb_config=ChromaDbConfig(chroma_settings={"allow_reset": True}))
```

should turn into this

```python
app = App(chromadb_config=ChromaDbConfig(allow_reset=True))
```

### Motivation, pitch

allow_reset should be directly configurable under ChromaDbConfig, without the need to pass it as a dict in the "advanced settings".

**Comment by Dev-Khant** [comment]
Can I pick it up @cachho?

**Comment by cachho** [comment]
Just make sure to update the actual code, tests and the error message

**Comment by Dev-Khant** [comment]
> Just make sure to update the actual code, tests and the error message

Yes
