### ISSUE TITLE
DOC: Update examples, tesla.com domain is not responsive

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#612]
### Issue with current documentation:

Doc examples using the tesla.com domain seem to be non-responsive, causing the app to hang up.

I experienced this and so does another user on our discord, I think it's best if we swap them for another source.

Having a working readme example is crucial.

**Comment by subhadip001** [comment]
can i contribute here , it will be good for me as this will be my first osc to some good project

**Comment by cachho** [comment]
> can i contribute here , it will be good for me as this will be my first osc to some good project

absolutely. Just find a good replacement and make sure to check readme and docs.

**Comment by subhadip001** [comment]
so you will assign me or i can just follow the docs to fork and do the changes , means i am asking is assignment is required ?
