### ISSUE TITLE
Add Huggingface embeddings

### ISSUE THREAD

**Issue by MaelSeed** [embedchain/embedchain#62]
I would appreciate it if you add Huggingface embeddings, because it would be free to use, in contrast to OpenAI's embeddings, which uses ada I believe. So something along those lines would be great:

`embeddings_model_name = "sentence-transformers/all-MiniLM-L6-v2"

embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)`

Altough I must admit that I do not know the difference between openAI and this model when it comes to embeddings, if anyone knows, please let me know what those differences are.

**Comment by taranjeet** [comment]
we support hugging face embeddings. Just need to make our docs clear that this support is already there.
closing this issue.
