### ISSUE TITLE
chore: bump example versions

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#621]
### 🐛 Describe the bug

Bump the version of embedchain used in examples. Of course you must also test it.

Open for anyone to pick up.

**Comment by taranjeet** [comment]
Opened specific issue for ease


https://github.com/embedchain/embedchain/issues/631
https://github.com/embedchain/embedchain/issues/632
https://github.com/embedchain/embedchain/issues/633

**Comment by taranjeet** [comment]
Closing this one.
