### ISSUE TITLE
Query Config not Found

### ISSUE THREAD

**Issue by AbrahimZaman360** [embedchain/embedchain#625]
### 🐛 Describe the bug

```python
from embedchain.config import InitConfig, QueryConfig
```

Cannot Import the Following...

**Comment by taranjeet** [comment]
Hey @AbrahimZaman360 , we updated the config so these configs dont exist as of now.
Can you please try

```
from embedchain.config import AppConfig, LlmConfig
```

**Comment by AbrahimZaman360** [comment]
Please Write it in Official Documentation.
Thanks

**Comment by taranjeet** [comment]
Hey @AbrahimZaman360 , apologies for the inconvenience . We are working on updating the docs.
