### ISSUE TITLE
refactor: make it clear what methods are private

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#628]
### 🚀 The feature

For intellisense to work efficiently, and for  anyone working on the package, it should be made clear what methods are private by prefixing them with `_`.

Private methods are not to be used by endusers. In other programming languages you can actually protect them, in python you can only hope that users don't use them. The underscore moves the back in the intellisense suggestions.

I think the worst offender is `retrieve from database`, the name suggests that it could be used in place of `query`, which it can't.

This goes for classes and files.

### Motivation, pitch

We have more user exposed methods now, for instance app.serialize and app.deserialize.

**Comment by taranjeet** [comment]
@cachho : can you please list down what all methods should be private here?

**Comment by cachho** [comment]
> @cachho : can you please list down what all methods should be private here?

I mean at that point I might aswell add the underscore myself. The answer is all methods that are not to be used by end users, mainly those are "intermediate" methods that are called by other methods and can't be called by themselves.

**Comment by taranjeet** [comment]
The next action here is to figure out what all methods are private.
This issue is up for grab
