### ISSUE TITLE
feature request: `load_and_embed_v2`: add `dry_run`

### ISSUE THREAD

**Issue by cachho** [embedchain/embedchain#630]
### 🚀 The feature

Can look at v1 for inspiration

### Motivation, pitch

-

**Comment by cachho** [comment]
@Dev-Khant do you maybe want to pick this up again? Sorry that I'm asking you again.

I'm also wondering why you placed it where you did in v1. Why not after the `new_metadatas`?

**Comment by Dev-Khant** [comment]
Sure @cachho I'll pick it up. 
The reason for not using `new_metadatas` was I thought that it was not necessary to show `app_id` or `hash`. But sorry I didn't notice the `metadata` that is passed as an argument. Will change it in the upcoming PR for v2
