### ISSUE TITLE
Rename _get_athrophic_answer to _get_answer in anthropic llm class

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#655]
### 🐛 Describe the bug

In file https://github.com/embedchain/embedchain/blob/main/embedchain/llm/antrophic.py, rename _get_anthropic_answer to_get_answer.

Also make sure that everything related to this work and doesn't break.

**Comment by Rhythm-08** [comment]
Hello, @taranjeet I would like to solve this issue.

**Comment by taranjeet** [comment]
Hey @Rhythm-08 , sure assigned it to you.
