### ISSUE TITLE
Rename _ge_get_athrophic_answert_gpt4all_answer to _get_answer in vertex ai llm class

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#658]
### 🐛 Describe the bug

In file https://github.com/embedchain/embedchain/blob/main/embedchain/llm/vertex_ai.py, rename _get_athrophic_answer to_get_answer.

Also make sure that everything related to this work and doesn't break.

**Comment by BattiniSandeep** [comment]
Hi, Would like to work on this basic issue. thanks

**Comment by taranjeet** [comment]
Hey @BattiniSandeep , assigned it to you.

**Comment by BattiniSandeep** [comment]
Hi @taranjeet 

![image](https://github.com/embedchain/embedchain/assets/76659791/ce404401-daec-4961-a16f-4f0c25c7d926)
Getting these errors while setting up the project. Unable to push the code after making the changes due to these error. 

Any idea why these error are showing up. 

thanks
Sandeep
