### ISSUE TITLE
Rename models/EmbeddingFunctions.py to follow snake case convention

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#659]
### 🐛 Describe the bug

listed file nam should follow snake case convention.
Also handle the related imports of this file and make sure that everything works.

**Comment by OsamaNabih** [comment]
Hey there, I'm interested in this issue
I made this https://github.com/embedchain/embedchain/pull/669 PR as a draft
When running `poetry run pytest` however I'm getting a lot f errors with the same message
`Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.`
Any hints?
