### ISSUE TITLE
Rename models/VectorDatabases.py to follow snake case convention

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#661]
### 🐛 Describe the bug

listed file name should follow snake case convention.
Also handle the related imports of this file and make sure that everything works.

**Comment by subhajit20** [comment]
@taranjeet working on it.

**Comment by githubashutoshsoni** [comment]
Hey @taranjeet , is this still available? I'm looking forward to taking this task.

**Comment by PatelKeviin** [comment]
This issue should be closed as it was merged a while ago?

**Comment by taranjeet** [comment]
thanks @PatelKeviin . closing this
