### ISSUE TITLE
Rename apps/PersonApp.py to follow snake case convention

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#667]
### 🐛 Describe the bug

listed file name should follow snake case convention.
Also handle the related imports of this file and make sure that everything works.

**Comment by rabroldan** [comment]
Hello can I take a shot at it and try doing this as my first issue?

**Comment by taranjeet** [comment]
Hey yeah, just assigned it to you.

**Comment by taranjeet** [comment]
Hey @rabroldan , feel free to reach out if any doubts.

**Comment by taranjeet** [comment]
this issue is up for grab

**Comment by Moracus** [comment]
I'd like to take this issue and resolve it, if it's still up. Also i was wondering , where's the "listed files" , whose casing needs to be changed?
