### ISSUE TITLE
Dropbox folder/instance as a data source

### ISSUE THREAD

**Issue by fishingelephants** [embedchain/embedchain#668]
### 🚀 The feature

Rather than adding one document at a time, enable the bot to ingest an entire Dropbox folder or directory structure.

### Motivation, pitch

Often times, the knowledge on which you want to train the bot is already curated. Pointing it to that repository rather than having to manually enter the URL of each and every file will save a lot of setup time and as well as make supporting more dynamic knowledge bases easier - you don't have to have a preconceived notion of how the knowledge is divided and across which files.

**Comment by Dev-Khant** [comment]
Closing because `dropbox` dataloader currently accepts folders or directory as input https://docs.embedchain.ai/components/data-sources/dropbox
