### ISSUE TITLE
Rename vectordbs/AddConfig.py to follow snake case convention

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#676]
### 🐛 Describe the bug

Listed file name should follow snake case convention.
Also handle the related imports of this file and make sure that everything works.

### Accepted file name
this_file_name_is_accepted.py

### Not accepted file name(s)
This_File_Name_Is_Not_Accepted.py
THIS_FILE_NAME_IS_NOT_ACCEPTED.py

**Comment by dev-ayush69** [comment]
Hi @taranjeet . I would like to take up this issue. Can you pls assign me this issue and also #677 ?

**Comment by taranjeet** [comment]
Hey @dev-ayush69 , just assigned it to you.
