### ISSUE TITLE
Support gpt4all integration via langchain

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#683]
### 🚀 The feature

Current gpt4all integration is barebones and doesn't use langchain.
langchain provides a unified interface.
https://python.langchain.com/docs/integrations/providers/gpt4all

### Motivation, pitch

* When we move to using gpt4all via langchain, our users can use langsmith for observability.
* Standard interface for llm helps in better code maintenance

**Comment by ShivamMenda** [comment]
@taranjeet I want to work on this feature, using langchain we can import it and I can use it to generate output. But I'm unsure how to integrate it with a large-scale project like this one. Is there any way you could guide me or explain the integration process so that I can contribute?

**Comment by taranjeet** [comment]
Hey @ShivamMenda , sure.
You can go through all the files in 
https://github.com/embedchain/embedchain/tree/main/embedchain/llm
to understand how each llm is integrated.

You can look at https://github.com/embedchain/embedchain/blob/main/embedchain/llm/vertex_ai.py for example to learn more about how this can be done using langchain.

Assigning it to you.

**Comment by ShivamMenda** [comment]
@taranjeet Sure thanks. I'll try it out.

**Comment by ShivamMenda** [comment]
@taranjeet added the integration. Please do check it out.

**Comment by taranjeet** [comment]
this is already live. Closing this.
