### ISSUE TITLE
Support cohere integration via langchain

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#684]
### 🚀 The feature

https://python.langchain.com/docs/integrations/providers/cohere

### Motivation, pitch

* We need to support more llms so that users have the flexibility of choosing whatever LLM they want to use.
* Langchain provides a standard interface for llms. This helps in better code maintenance and also helps in better observability.

**Comment by Dev-Khant** [comment]
@taranjeet Can I pick it up?
Here we will have to create a `CohereApp`, right?

**Comment by sidmohanty11** [comment]
Hello @taranjeet, can I please pick this up?
