### ISSUE TITLE
Support AWS bedrock LLM

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#687]
### 🚀 The feature

https://python.langchain.com/docs/integrations/platforms/aws

### Motivation, pitch

* We need to support more llms so that users have the flexibility of choosing whatever LLM they want to use.
* Langchain provides a standard interface for llms. This helps in better code maintenance and also helps in better observability.

**Comment by KapilM26** [comment]
@taranjeet please assign this to me

**Comment by krrishdholakia** [comment]
Hey @taranjeet @KapilM26 @sidmohanty11 you can do this with ChatLiteLLM in Langchain 

```python
from langchain.chat_models import ChatLiteLLM
from langchain.schema import AIMessage, HumanMessage, SystemMessage

chat = ChatLiteLLM(model="bedrock/anthropic.claude-v2")

messages = [
    HumanMessage(
        content="Translate this sentence from English to French. I love programming."
    )
]
chat(messages)
```

Benefit over using the bedrock integration? 
Bedrock supports: 
- Anthropic 
- Cohere
- Amazon Titan 
- AI21

Each has their own prompt formatting and input params (langchain doesn't natively map this).
