### ISSUE TITLE
Add support for lance db as vector database

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#690]
### 🚀 The feature

- add a new vector database
- https://lancedb.com/

### Motivation, pitch

This gives more flexibility to the user to use any vector database of their own choice.

**Comment by SudhanshuJoshi09** [comment]
Hey @taranjeet, Can I pick up this issue ?

**Comment by shubham1234098** [comment]
i am wanna work on it 👍👍

**Comment by shubham1234098** [comment]
i am working on it 👍👍

**Comment by BlacPharaoh** [comment]
Can I pick up this issue?
