### ISSUE TITLE
Setup codecov.io to measure test coverage

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#696]
### 🚀 The feature

We need to setup codecov.io to measure code coverage.

### Motivation, pitch

As the package is growing, we need to add test for each piece of code. For this we need to measure the coverage right now and then track it from here.

**Comment by morgoth9808** [comment]
Hey @taranjeet  I want to work on this issue

**Comment by taranjeet** [comment]
Hey @morgoth9808 , assigned it to you.

**Comment by morgoth9808** [comment]
Hey @taranjeet can you tell me which method should i use to generate the test coverage file I have been using :
```
coverage run -m pytest
``` 
And its generating errors
