### ISSUE TITLE
Use app.db.reset() instead of app.reset()

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#711]
### 🐛 Describe the bug

🐛 Describe the bug
Following code snippet gives a warning

```
from embedchain import App
app = App()
app.count()
[root] DEPRECATION WARNING: Please use `app.db.reset()` instead of `App.reset()`.
```

reset function resets the database. 

We should update code to fix the warning.

**Comment by subhajit20** [comment]
@taranjeet  Hey should I change the following code to `return app.reset()` ?
https://github.com/embedchain/embedchain/blob/70f2de4fd324fc7df8caef734554938115b78464/embedchain/embedchain.py#L552

**Comment by taranjeet** [comment]
Hey @subhajit20 , thats almost right but will advice if you spend some more time in looking through the code and making sure that all the possible scenarios are covered. Making sure that tests don't break is one of the way. Other can be looking for instance of reset and then manually replicating the situation yourself.
Let me know if there are any doubts.

**Comment by taranjeet** [comment]
Let me know if you are working on this @subhajit20 . Will assign it to you.

**Comment by subhajit20** [comment]
> Let me know if you are working on this @subhajit20 . Will assign it to you.

Want to work on it.
You can assign it to me.

**Comment by taranjeet** [comment]
@subhajit20 assigned it to you.

**Comment by BlacPharaoh** [comment]
Can this be assigned to me?

**Comment by deshraj** [comment]
This is not needed anymore so closing this issue.
