### ISSUE TITLE
Add support for xml file format

### ISSUE THREAD

**Issue by fredericcogny** [embedchain/embedchain#714]
### 🚀 The feature

We need to support XML file format. So ideally the user should be able to do

```
from embedchain import App

app = App()

app.add("/path/to/my_xml_file.xml") 
# or
app.add("/path/to/my_xml_file.xml", data_type="xml")
```

This will involve writing the logic to auto-detect that its an XML file, data loader, and data chunker. 

### Motivation, pitch

Many structured documents are stored in XML format. Having an out of the box support for general XML files would be very helpful

**Comment by taranjeet** [comment]
Thanks @fredericcogny for opening the issue.

**Comment by Dev-Khant** [comment]
Can I pick it up @taranjeet?
