### ISSUE TITLE
sitemap loading does not work with with sitemap.xml

### ISSUE THREAD

**Issue by Lato-Masi** [embedchain/embedchain#715]
### 🐛 Describe the bug

using this sitemap as the example test.   https://keto-mojo.com/sitemap_index.xml
note: that sitemap list other sitemaps.  It uses Yoast SEO to generate the sitemap, so this is going to be something common for wordpress sites that have that common plug-in.

This code produces the error.  the meta tag does not indicate it is XML but the URL uses it and then links are all XML extensions.
noesis_bot.add("https://keto-mojo.com/sitemap_index.xml", data_type = "sitemap")
/usr/local/lib/python3.10/dist-packages/embedchain/data_formatter/data_formatter.py
line 117
ValueError: Unsupported data type: DataType.SITEMAP

Testing with an RSS feed which is XML I got another error
noesis_bot.add("http://rss.cnn.com/rss/cnn_topstories.rss", "web_page")
/usr/local/lib/python3.10/dist-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

I think the section of code that needs to be fixed is this one
embedchain/loaders/sitemap.py

Were it auto-detect if a URL has an XML extension but it is not XML, versus the other case where it is an RSS feed but it is XML.

To fix this so it works as a webcrawler starting with the site map might need something a bit more complete.  See the example at this link.  
[https://practicaldatascience.co.uk/data-science/how-to-parse-xml-sitemaps-using-python](https://practicaldatascience.co.uk/data-science/how-to-parse-xml-sitemaps-using-python)

this recommendation in the data_types file did not work.
from: docs/advanced/data_types.mdx
_### Forcing a data type
To omit any issues with the data type detection, you can **force** a data_type by adding it as a `add` method argument.
The examples below show you the keyword to force the respective `data_type`.
Forcing can also be used for edge cases, such as interpreting a sitemap as a web_page, for reading its raw text instead of following links.
### Sitemap
Add all web pages from an xml-sitemap. Filters non-text files. Use the data_type as `sitemap`. Eg:
```python
app.add('https://example.com/sitemap.xml', data_type='sitemap')
```_

using the webpage loader instead of sitemap does pass through but it only fetches 4 links then stops
noesis_bot.add("https://keto-mojo.com/sitemap_index.xml", "web_page")
Successfully saved https://keto-mojo.com/sitemap_index.xml (DataType.WEB_PAGE). New chunks count: 4
So this wasn't the solution.

**Comment by deshraj** [comment]
This issue is resolved now.
