### ISSUE TITLE
DOC: Add link to slack

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#718]
### Issue with current documentation:

In the [documentation], add link to slack in the top nav bar and footer.

Link to slack: https://join.slack.com/t/embedchain/shared_invite/zt-22uwz3c46-Zg7cIh5rOBteT_xe1jwLDw

Refer mintlify documentation for information regarding how to add link in top nav bar and footer

- https://mintlify.com/docs/settings/ctas-footers

Ideally `topbarLinks` and `footerSocials` key in `mint.json` should be updated along side other needed changes.

**Comment by malik-vishu** [comment]
@taranjeet Can you assign this to me?

**Comment by taranjeet** [comment]
Hey @malik-vishu : I just saw your comment and till then the PR was already raised and merged. You can pick up other issues There are a lot of issues that need help.

@Tushar-kalsi : thanks
