### ISSUE TITLE
Project Tools 

### ISSUE THREAD

**Issue by amjadraza** [embedchain/embedchain#72]
Setup Following Project Management Tools

1. Project Package and Environment Manager: Poetry is recommended
2. `pytests` and `pylint` setup
3. Contributing Guide
4. Sphnix Documentation and deploying on the `readthedocs` server
5. `Docstrings` for API : Google Style is recommended.
6. CI/CD workflows

>I can help with above

**Comment by amjadraza** [comment]
@taranjeet Let me know if no one is working on the above improvements.

**Comment by taranjeet** [comment]
tagging @deshraj . feel free to close this if everything is done, or open new issue for the pointers mentioned here.
thanks @amjadraza for the help here.

**Comment by Dev-Khant** [comment]
Closing this issue since all the things mentioned above are added.
Thanks a lot @amjadraza!
