### ISSUE TITLE
Using GPT-4 for prompting 

### ISSUE THREAD

**Issue by GabCores** [embedchain/embedchain#73]
Hi there, I see that the framework is using GPT-3.5 last release  , for doing prompting 
How I can change to GPT-4 ?

My Best for this project !
Regards

**Comment by danielhangan** [comment]
also have the same question.

**Comment by josebenitezg** [comment]
I opened a [PR](https://github.com/embedchain/embedchain/pull/100) for this. Hope they merge soon!

**Comment by taranjeet** [comment]
we support gpt-4 model option via QueryConfig and ChatConfig.
But the docs are not clear. Tracking request for updating the docs here: https://github.com/embedchain/embedchain/issues/73

Closing this issue.
