### ISSUE TITLE
Follow snake case convention in folder vectordb

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#734]
### 🐛 Describe the bug

Located at  embedchain/config/vectordb

It should be vector_db.

This task will involve changing the relevant imports everywhere and making sure that tests pass and nothing breaks.

**Comment by Psudopodiya** [comment]
How do i test it out some way to run the code ?

**Comment by Prikshit7766** [comment]
@Psudopodiya 
Are you currently working on this task, or should I go ahead and start making the necessary changes?

**Comment by Psudopodiya** [comment]
> @Psudopodiya Are you currently working on this task, or should I go ahead and start making the necessary changes?

Sure go ahead with this one. Sorry do not have time for it right now

**Comment by shubham1234098** [comment]
hello can i contribute on it??
