### ISSUE TITLE
[Feature Request] Auto-Detect data-type, make the it optional

### ISSUE THREAD

**Issue by ianderrington** [embedchain/embedchain#76]
First off... Great job!!! Simple and tight code. Much appreciate you making/sharing it. 

There was one quick suggestion I had: In order to minimize boilerplate code, it would be good to modify the interface to make the `file_type` variable optional and detected based on the input content. If the variable is defined then the code would check the file to ensure that it is of the specified type. 

This ease-of-life modification should be added early in development to minimize more extensive refactors down the line. 

But I wholly understand if you have a different design goal for making this a required input.

**Comment by cachho** [comment]
#380 will resolve this

**Comment by taranjeet** [comment]
Closing this issue, since we are already tracking in #380
