### ISSUE TITLE
Bug: Vector DB Query methods should take in a string and not list[str] for input_query argument

### ISSUE THREAD

**Issue by rupeshbansal** [embedchain/embedchain#776]
### 🐛 Describe the bug

For all the vectordb classes (<[embedchain/vectordb/...>]), the `query` function argument is a bit out of place. The argument `input_query` should be a string, but is instead a list of strings, impacting the readability of the code.

**Comment by Dev-Khant** [comment]
Can I pick this up? @rupeshbansal
