### ISSUE TITLE
Azure_OpenAI Embedder support is not available.

### ISSUE THREAD

**Issue by SandeepPasula898** [embedchain/embedchain#779]
### 🐛 Describe the bug

In EmbedChain Documentation(https://docs.embedchain.ai/advanced/app_types#embedder) it is mentioned we can choose Azure_OpenAI embedder, but I can't see any such support in library. Please check and confirm.

**Comment by BlacPharaoh** [comment]
I will work on this

**Comment by deshraj** [comment]
Hey @SandeepPasula898, this issue is already resolved. We have also added a jupyter notebook for you to test the Azure OpenAI integration with Embedchain: https://github.com/embedchain/embedchain/blob/main/notebooks/azure-openai.ipynb

**Comment by SandeepPasula898** [comment]
Hey thanks! I will try it out.

**Comment by thezanke** [comment]
This does not work without the patch in https://github.com/langchain-ai/langchain/commit/f0198354d93e7ba8b615b8fd845223c88ea4ed2b which updates langchain to add chunk_size defaults for azure; without that we get:

> InvalidRequestError: Too many inputs. The max number of inputs is 16. We hope to increase the number of inputs per request soon. 

Is it possible to update to langchain >=0.0.296 (where the fix is introduced)?

Thanks!

**Comment by deshraj** [comment]
> This does not work without the patch in [langchain-ai/langchain@f019835](https://github.com/langchain-ai/langchain/commit/f0198354d93e7ba8b615b8fd845223c88ea4ed2b) which updates langchain to add chunk_size defaults for azure; without that we get:
> 
> > InvalidRequestError: Too many inputs. The max number of inputs is 16. We hope to increase the number of inputs per request soon.
> 
> Is it possible to update to langchain >=0.0.296 (where the fix is introduced)?
> 
> Thanks!

Here is the PR https://github.com/embedchain/embedchain/pull/875 @thezanke :)
