### ISSUE TITLE
Support of QdrantDB

### ISSUE THREAD

**Issue by SandeepPasula898** [embedchain/embedchain#793]
### 🚀 The feature

Hello, currently this tool seems to be supporting ChromaDB and other 2 search services. Can we have support for QdrantDB or other like Azure cognitive search?

### Motivation, pitch

I am trying to add Qdrant or Cognitive search as per our customer requests. May I know what it takes to add these DB support? I s there a low level documentation to understand the dynamics of this tool and add something new to it? or can we expect these new platforms support in future? Thanks

**Comment by taranjeet** [comment]
Hey @SandeepPasula898  thanks for opening this.
We already have an issue to track this request

https://github.com/embedchain/embedchain/issues/112

Will close this. If you want to add anything, feel free to add there.
