### ISSUE TITLE
Add support for OpenAI function calling

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#796]
### 🚀 The feature

Users have requested this feature where they want to do OpenAI function calling using Embedchain. See request here: 

<img width="647" alt="Screenshot 2023-10-12 at 10 27 25 AM" src="https://github.com/embedchain/embedchain/assets/2945708/fcf002d7-cd6e-4e49-92f9-60c768098b49">

### Motivation, pitch

This is going to be really useful for devs who are using OpenAI LLMs so we should add support for it.

**Comment by ShatilKhan** [comment]
Hi @deshraj , can you provide some guidance on how to achieve this?
I'd like to work on this

**Comment by Dev-Khant** [comment]
Can I pick this up @deshraj?

**Comment by deshraj** [comment]
Yes, go for it.

**Comment by Adity20** [comment]
Hi, Can you assign this issue to me

**Comment by Dev-Khant** [comment]
Can you give more context on it @deshraj?
Do we create a separate class for it or add it in `OpenAILlm`

**Comment by deshraj** [comment]
We want to add it to the OpenAILlm class itself.

**Comment by deshraj** [comment]
@Dev-Khant any updates on this? We would like to do it ourselves. If you don't have bandwidth, please let us know so that we can assign to someone else.

**Comment by Dev-Khant** [comment]
Really sorry @deshraj I'm busy with my exams. Please you can assign it to someone else. I'll start contribution once I'm done with exams.
