### ISSUE TITLE
Insert Local File instead of link

### ISSUE THREAD

**Issue by masteryodaa** [embedchain/embedchain#81]
How do I train the model with my local files? Suppose I have a pdf in root directory and I want to add it like mygpt.add("pdf_file", "book.pdf"). Is it possible?

**Comment by jamiequint** [comment]
you could just read the code you know :)

my_bot.add("pdf_file",'/Users/youruser/Downloads/yourpdf.pdf')

**Comment by masteryodaa** [comment]
thanks.
