### ISSUE TITLE
Add support for Ollama

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#810]
### 🚀 The feature

We want to add support for LLMs and embedding models through Langchain.

You can find the Ollama docs in Langchain here: https://python.langchain.com/docs/integrations/llms/ollama

### Motivation, pitch

Requested on twitter: https://twitter.com/Blaq_Mo/status/1713899522399580335

**Comment by rsato10** [comment]
Hello, can I work on issue #810.

**Comment by deshraj** [comment]
> Hello, can I work on issue #810.
> 
> 

@rsato10 sure, go for it.

**Comment by SrijanSahaySrivastava** [comment]
may i please work on it? i have some plans laid out for it

**Comment by deshraj** [comment]
@SrijanSahaySrivastava sure, go for it.

**Comment by rsato10** [comment]
@deshraj Sorry, I've been having midterms. So you can assign it to @SrijanSahaySrivastava. When I have free time could I contribute on other issues?

**Comment by deshraj** [comment]
Sounds good @rsato10. Good luck with your midterms. 

@SrijanSahaySrivastava please feel free to work on this issue.

**Comment by SrijanSahaySrivastava** [comment]
I'll start work on it ASAP (sorry for delay, My uni had to conduct exams at the same time :P )

**Comment by dhruv1710** [comment]
Is it open? can I work on it?

**Comment by sukkritsharmaofficial** [comment]
Let me know if you need some help with this, I'm open to work on this!

**Comment by deshraj** [comment]
@SrijanSahaySrivastava are you still working on this issue? if not, @dhruv1710 you can work on this.

**Comment by deshraj** [comment]
@sukkritsharmaofficial please feel free to pick up any other open issues :)

**Comment by SrijanSahaySrivastava** [comment]
Yeah I'm having some trouble working from my hostel, if you guys want I can upload my progress and someone else can pick from there

**Comment by tomtom215** [comment]
Bump as this would be my main use-case for trying out embedchain 
(hope exams went well for those in this thread!)

**Comment by sukkritsharmaofficial** [comment]
Anything on this? This would be a great add on, let me know if no ones working on this @deshraj, would love to pick this up

**Comment by deshraj** [comment]
@sukkritsharmaofficial yes feel free to work on this.
