### ISSUE TITLE
NodeJS TypeError: First parameter has member 'readable' that is not a ReadableStream.

### ISSUE THREAD

**Issue by poetsmeniet** [embedchain/embedchain#812]
### 🐛 Describe the bug

I'm trying to create a bot using Node 18+ (I tried multiple versions), but receive the following error:

`node_modules/openai/node_modules/web-streams-polyfill/dist/polyfill.js:362
            throw new TypeError(context + " is not a ReadableStream.");
                  ^
TypeError: First parameter has member 'readable' that is not a ReadableStream`

I installed using npm i embedchain --save

The code I'm using:

`const dotenv = require("dotenv");
dotenv.config();

const { App } = require("embedchain");

async function askBot() {
    const myBot = await App();

    const myPrompt = "Who where his parents, and how old was he?";
    const res = await myBot.query(myPrompt);

    console.log(res);
}

askBot();`

**Comment by poetsmeniet** [comment]
I don't know why the code block is messed up, sorry

**Comment by Dev-Khant** [comment]
Closing this issue as EmbedchainJS is no longer available.
