### ISSUE TITLE
Resetting a db collection doesn't remove previous source hashes

### ISSUE THREAD

**Issue by fabioferreira3** [embedchain/embedchain#860]
### 🐛 Describe the bug

When deleting a collection with App().db.client.delete_collection(collection_name), the source hashes are not removed from the database, which means you're unable to re-add the same source again.

For example:

- User adds a source URL using App().add('source_url').
- User deletes the collection where the source was indexed.
- User tries to re-add/index the same source again.
- Since the source hash is still present, it will skip the embedding and won't index this source.

I'm not an experienced Python developer but I believe that's where this skip occurs:

embedchain.py - Lines 218 - 230
```
# `source_hash` is the md5 hash of the source argument
        hash_object = hashlib.md5(str(source).encode("utf-8"))
        source_hash = hash_object.hexdigest()

        # Check if the data hash already exists, if so, skip the addition
        self.cursor.execute(
            "SELECT 1 FROM data_sources WHERE hash = ? AND pipeline_id = ?", (source_hash, self.config.id)
        )
        existing_data = self.cursor.fetchone()

        if existing_data:
            print(f"Data with hash {source_hash} already exists. Skipping addition.")
            return source_hash
```

**Comment by taranjeet** [comment]
hey @fabioferreira3 thanks for opening the issue. 
@sidmohanty11 : assigning this to you.

**Comment by deshraj** [comment]
This issue is already resolved btw. Hence, closing it.
