### ISSUE TITLE
Can we upgrade to openai (>=0.28.0,<0.29)?

### ISSUE THREAD

**Issue by ninjaa** [embedchain/embedchain#865]
### 🚀 The feature

Also using the instructor library
https://github.com/jxnl/instructor

To extract features from queries to enhance semantic searching. But it requires openai >= 0.28, while embedchain is hardcoded to <0.28. 

Can the openai version be bumped please?

Let me know

### Motivation, pitch

Instructor is an amazing library - check it out.

This use case explains it all

```
import instructor
from pydantic import BaseModel, field_validator

# Apply the patch to the OpenAI client
instructor.patch()

class UserDetails(BaseModel):
    name: str
    age: int

    @field_validator("name")
    @classmethod
    def validate_name(cls, v):
        if v.upper() != v:
            raise ValueError("Name must be in uppercase.")
        return v

model = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    response_model=UserDetails,
    max_retries=2,
    messages=[
        {"role": "user", "content": "Extract jason is 25 years old"},
    ],
)

assert model.name == "JASON"
```

We are using it to extract keywords for semantic search keyword matching.

**Comment by deshraj** [comment]
Thanks @ninjaa for opening the issue. I will take care of this. Will release a new version of the package soon.

**Comment by ninjaa** [comment]
Woo hoo
