### ISSUE TITLE
Add support for postgres as vector database (with pgvector)

### ISSUE THREAD

**Issue by hleroy** [embedchain/embedchain#873]
### 🚀 The feature

add postgres support with pgvector https://github.com/pgvector/pgvector

### Motivation, pitch

This gives more flexibility to the user to use any vector database of their own choice.

pgvector has a Python library (https://github.com/pgvector/pgvector-python). It's easy to integrate with a Django website using the same database and leveraging new field type `VectorField`.

**Comment by deshraj** [comment]
Thanks @hleroy for creating the issue. We will prioritize this and get it done soon.

**Comment by deven298** [comment]
Follow [issue# 899](https://github.com/embedchain/embedchain/issues/899) to track this.
