### ISSUE TITLE
Ability to add JSON files from external URLs 

### ISSUE THREAD

**Issue by fabioferreira3** [embedchain/embedchain#874]
### 🚀 The feature

As already occurs with PDFs and Docx file formats, users should be able to add (embed) JSON files by passing an external URL of their location instead of their local paths.

### Motivation, pitch

Currently, users can only add JSON files stored locally by passing their local path to the App().add() method.

**Comment by deshraj** [comment]
Thanks @fabioferreira3 for opening the issue. This is something which is already on our radar. We will make it happen soon.

**Comment by deven298** [comment]
Thanks @fabioferreira3. Here is the PR which introduces that feature - [878](https://github.com/embedchain/embedchain/pull/878/). Have fun builidng!
