### ISSUE TITLE
Sitemap loader doesn't work with local files

### ISSUE THREAD

**Issue by deshraj** [embedchain/embedchain#877]
### 🐛 Describe the bug

Currently, the sitemap loader only works with urls and not with file present on a local filesystem. We want to add support for it like all other data loaders which support both loading from a url and loading from local file system.

Issue was reported here on slack community: https://embedchain.slack.com/archives/C05RG7CJKC6/p1698393783510609

**Comment by vishutupili** [comment]
Hi, I would like to work on this issue. Could you please assign me to it.
