### ISSUE TITLE
Support for various open source embeddings

### ISSUE THREAD

**Issue by ranjancse26** [embedchain/embedchain#880]
### 🚀 The feature

Request to extend and support for various open source embeddings like sentence bert, instruct embedding etc. I see from the current codebase that the following are supported among which Gpt4All is the only open source option.

    OPENAI = "OPENAI"
    HUGGING_FACE = "HUGGING_FACE"
    VERTEX_AI = "VERTEX_AI"
    GPT4ALL = "GPT4ALL"

### Motivation, pitch

Support for open source embeddings and keep the code base up to date as the open source is evolving.

**Comment by Dev-Khant** [comment]
Here `huggingface` does support open source embedding models. https://docs.embedchain.ai/components/embedding-models#hugging-face
