### ISSUE TITLE
When I rerun the app the DB context is always empty

### ISSUE THREAD

**Issue by SpeedOfSpin** [embedchain/embedchain#884]
### 🐛 Describe the bug

I get the same issue locally as I do in the given example on the Embedchain website.

[OpenAI Example](https://colab.research.google.com/github/embedchain/embedchain/blob/main/notebooks/openai.ipynb#scrollTo=F3QaED3tPGYe)

```
import os
from embedchain import Pipeline as App

os.environ["OPENAI_API_KEY"] = "sk-"

config = """
llm:
  provider: openai
  config:
    model: gpt-35-turbo
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false

embedder:
  provider: openai
  config:
    model: text-embedding-ada-002
    deployment_name: ec_embeddings_ada_002
"""

# Write the multi-line string to a YAML file
with open('openai.yaml', 'w') as file:
    file.write(config)

app = App.from_config(yaml_path="openai.yaml")

# Rerun but don't add it to the DB. I expected it to already be there.
app.add("https://www.forbes.com/profile/elon-musk")

app.search("How much is musk worth")
# Correct data printed

app = App.from_config(yaml_path="openai.yaml")
app.search("How much is musk worth")
# No data printed
```

If I run it the first time and add the url I get the context printed out as expected. 
If I reinit the app I get nothing.

I would have thought that after adding it once it should be there on the next run.

I know I'm doing something stupid but can't figure it out.

Thanks
SoS

**Comment by deshraj** [comment]
Hey, I think you forgot to add the following on top of your config file:

```yaml
pipeline:
  config:
    name: My App
    id: app_1  # Make sure you set the id if you want to use already added data
```

Let me know if this doesn't work.

**Comment by SpeedOfSpin** [comment]
Thats brilliant thank you! I can't see that anywhere. Was I missing something.

**Comment by SpeedOfSpin** [comment]
Looks like that config has been removed in the latest version so I am getting the same issue where it adds the document every time. If I dont add it then the query is empty.

**Comment by SpeedOfSpin** [comment]
Instead of pipeline use this
app:
  config:
    id: 'app_1'

**Comment by Korayem** [comment]
That worked!!
> Instead of pipeline use this app: config: id: 'app_1'

[Docs talk about reusing without mentoining config at all](https://docs.embedchain.ai/components/data-sources/data-type-handling#reusing-a-vector-database)

**Comment by deshraj** [comment]
Thanks @Korayem for the comment. Will update the docs and fix it.

**Comment by deshraj** [comment]
Fixed the docs: https://github.com/embedchain/embedchain/pull/1289 :)
