### ISSUE TITLE
Can I use a PDFLoader of my own choice?

### ISSUE THREAD

**Issue by aby-chopda-psl** [embedchain/embedchain#887]
### 🚀 The feature

Is there a way I can use a PDFLoader I want or try out different loaders and see which works best for me? Any helps or solutions are appreciated!

### Motivation, pitch

I am trying to use embedchain to create a RAG structure. But the PDFLoader it might be using internally does not capture the data (tabular data) correctly.

**Comment by deshraj** [comment]
Hey @aby-chopda-psl, thanks for opening the issue. Can you please provide an example of what kind of pdf is not working?

**Comment by aby-chopda-psl** [comment]
I am using customer sensitive data...so I will not be able to show you the exact data. But let me give you some similar example.

Mostly is it tabular data that it cannot understand....It will align one column together then read other column and so on... 
Similarly if there are nested tables in a pdf, It will either read outer table data only or read half of inner table data....or just ignore the table all together.


<img width="464" alt="image" src="https://github.com/embedchain/embedchain/assets/145012669/36f678cd-b863-49d7-99b5-af08aa9ea5a3">

So in this example, the criteria column in one line, then read the exemplary performance column in one line and so on...
What I have observed was (https://github.com/nlmatics/llmsherpa)  worked better overall for pdfs. So i wanted to try my loading phase with it.

blogpost link for llmsherpa : https://blog.llamaindex.ai/mastering-pdfs-extracting-sections-headings-paragraphs-and-tables-with-cutting-edge-parser-faea18870125

**Comment by deven298** [comment]
@aby-chopda-psl We have added the support to be able to use custom loader and chunker of your choice in the latest version of Embedchain. Please refer to the [documentation](https://docs.embedchain.ai/data-sources/custom) for more details and let us know if you run into issues or the docs are not easy to follow.
