### ISSUE TITLE
Embedchain ElasticSearch: 'mapper_parsing_exception' 

### ISSUE THREAD

**Issue by ghoshaishik505** [embedchain/embedchain#888]
Hi,
When trying to embed documents in ElasticSearch (running in my localhost) through Embedchain Elastic Search wrapper, I am getting the following error message.
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Mapping definition for [embeddings] has unsupported parameters:  [index : false]')

What could be the possible fix for this?

ElasticSearch python client version: elasticsearch    7.13.1
Elastic-Transport: elastic-transport    7.15.0
Embedchain version: Version: 0.0.88
I am using ElasticSearch 7.9.0.

**Comment by deshraj** [comment]
Hi @ghoshaishik505, thanks for opening this issue. We will look into this issue and get back to you soon.

**Comment by deven298** [comment]
@ghoshaishik505 seems like you are using a very old version of elasticsearch. We are using `>=v8.x` which does not support `mapping types`. Checkout this source to migrate to newer version of [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html)

**Comment by ghoshaishik505** [comment]
Thanks @deven298 .
