### ISSUE TITLE
DEFAULT collect_metrics to false

### ISSUE THREAD

**Issue by firetix** [embedchain/embedchain#893]
### 🐛 Describe the bug

Hello,

I am currently working on a project using EmbedChain with RAG. I noticed that metrics are being sent to EmbedChain by default. For clarity and in the interest of user privacy, might I suggest changing the default setting to "NO"? This would enhance trust and transparency for users of the platform.

Thank you for considering this feedback.

Best regards,
Simo

**Comment by deshraj** [comment]
Hi @firetix, thank you for bringing this up. We appreciate your feedback. The telemetry is on by default to improve the experience of the platform. If we disable it, then it is quite likely that we won't get any data to see the usage pattern and hence won't be able to improve the package and the platform.

We will, although, make it more obvious to let users know that the telemetry is on and show instructions on how to disable it in the logs itself whenever someone is creating an app.

Thank you for your understanding.

**Comment by deshraj** [comment]
Created an issue for the same here: https://github.com/embedchain/embedchain/issues/894

**Comment by firetix** [comment]
I appreciate your perspective on the matter. However, I'd like to emphasize that many prominent organizations may be hesitant to adopt this library due to its default behavior. Ensuring user privacy and trust is paramount, and any perceived breach of this could deter potential users. I strongly recommend reconsidering this approach.

**Comment by deshraj** [comment]
Hello @firetix,

Thank you for your response. I completely agree that privacy and trust are paramount, and we highly value the security and privacy of our users. We are committed to being transparent about the anonymous data we collect, enabling users to disable it before transitioning to the production phase with Embedchain.

As an open-source project, it is imperative for us to have anonymous telemetry enabled by default to enhance the project effectively. It's worth noting that many popular open-source projects follow a similar approach with telemetry enabled by default.

For further insights on the topic of anonymous telemetry in open-source projects, I recommend reading the informative blog post by Posthog: https://posthog.com/blog/open-source-telemetry-ethical

Thank you for your understanding.

**Comment by chaliy** [comment]
We will be forced to recreate metrics instead of using this library, just because we cannot afford to use the library with out-out telemetry. Sorry.
