### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'Embedding'

### ISSUE THREAD

**Issue by Sukii** [embedchain/embedchain#917]
### 🐛 Describe the bug

# AttributeError: module 'openai' has no attribute 'Embedding'

Default Google Collab page raises this error.

**Comment by deshraj** [comment]
Thanks for reporting. You can resolve this issue for now by doing `pip install openai==0.28.1`

Chroma folks are fixing the issue in the meantime: https://github.com/chroma-core/chroma/issues/1340

**Comment by Sukii** [comment]
Yes, it did resole with downgrading `openai` as you mentioned.

Thanks!
