### ISSUE TITLE
Issue from chromadb

### ISSUE THREAD

**Issue by ghoshaishik505** [embedchain/embedchain#926]
### 🐛 

When instantiating a testbot with the default config.yaml, the following error comes up

'''
MyDir\env\Lib\site-packages\langchain\embeddings\openai.py:320: UserWarning: If you have openai>=1.0.0 installed and are using Azure, please use the `AzureOpenAIEmbeddings` class. warnings.warn( Traceback (most recent call last): File "MyDir\train.py", line 26, in <module> test_bot = App.from_config(yaml_path="config.yaml") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\embedchain\apps\app.py", line 157, in from_config return cls(config=app_config, llm=llm, db=db, embedder=embedder, chunker=chunker_config_data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\embedchain\apps\app.py", line 121, in _init_ super()._init(config, llm=llm, db=db, embedder=embedder, system_prompt=system_prompt) File "MyDir\env\Lib\site-packages\embedchain\embedchain.py", line 75, in __init_ self.db.initialize() File "MyDir\env\Lib\site-packages\embedchain\vectordb\chroma.py", line 71, in _initialize self._get_or_create_collection(self.config.collection_name) File "MyDir\env\Lib\site-packages\embedchain\vectordb\chroma.py", line 100, in _get_or_create_collection self.collection = self.client.get_or_create_collection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\chromadb\api\client.py", line 226, in get_or_create_collection return self._server.get_or_create_collection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\chromadb\telemetry\opentelemetry\init.py", line 127, in wrapper return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\chromadb\api\segment.py", line 216, in get_or_create_collection return self.create_collection( # type: ignore ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\chromadb\telemetry\opentelemetry\init.py", line 127, in wrapper return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\chromadb\api\segment.py", line 190, in create_collection return Collection( ^^^^^^^^^^^ File "MyDir\env\Lib\site-packages\chromadb\api\models\Collection.py", line 85, in __init_ validate_embedding_function(embedding_function) File "MyDir\env\Lib\site-packages\chromadb\api\types.py", line 210, in validate_embedding_function raise ValueError( ValueError: Expected EmbeddingFunction._call_ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs']) Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface. Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023
'''

**Comment by deshraj** [comment]
Thanks for reporting. We are working on a fix for this.
