### ISSUE TITLE
Run CI build pipelines only when needed

### ISSUE THREAD

**Issue by sidmohanty11** [embedchain/embedchain#935]
### 🚀 The feature

Run CI build pipelines only when any changes are done to the `/embedchain` and/or `/tests` directory.

### Motivation, pitch

This will remove unnecessary build calls while contributing to docs or examples etc

**Comment by deshraj** [comment]
Yeah, sounds like a good idea but we should be careful since we will add tests for the examples as well going forward to make sure that the examples are compatible and working with the embedchain version.

**Comment by deshraj** [comment]
For now, I think we can skip tests if there are changes only in `/docs` dir
