### ISSUE TITLE
Binary flag to indicate if model is able to answer from the context

### ISSUE THREAD

**Issue by gunajack** [embedchain/embedchain#939]
### 🚀 The feature

Hi,

Is there a way to detect with certainty that answer is (or not) in the context?
Guessing from answer is not that simple, as it sometimes replies from it's own material not present in the context.
A binary flag would work better as then we can pipe it to next model etc.

 Thanks,
 Guna

### Motivation, pitch

Yes, we want to be able to handle failure exceptions of the model.

**Comment by Dev-Khant** [comment]
Hi @gunajack, It would be better if you use evaluation methods to improve the accuracy of the answers. This will help https://docs.embedchain.ai/components/evaluation.

Closing this issue because we already have an evaluation framework in place.
