### ISSUE TITLE
Sqlite 

### ISSUE THREAD

**Issue by Yusufibin** [embedchain/embedchain#940]
### 🐛 Describe the bug

I don't know why but I have this bug that persists .

Traceback (most recent call last):
  File "/home/user/app/app.py", line 5, in <module>
    app = App.from_config(yaml_path="config.yaml") 
  File "/home/user/.local/lib/python3.10/site-packages/embedchain/pipeline.py", line 381, in from_config
    llm = LlmFactory.create(llm_provider, llm_config_data.get("config", {}))
  File "/home/user/.local/lib/python3.10/site-packages/embedchain/factory.py", line 37, in create
    return llm_class(config=llm_config_class(**config_data))
  File "/home/user/.local/lib/python3.10/site-packages/embedchain/llm/huggingface.py", line 26, in __init__
    super().__init__(config=config)
  File "/home/user/.local/lib/python3.10/site-packages/embedchain/llm/base.py", line 27, in __init__
    self.memory = ECChatMemory()
  File "/home/user/.local/lib/python3.10/site-packages/embedchain/memory/base.py", line 26, in __init__
    with sqlite3.connect(SQLITE_PATH) as self.connection:
sqlite3.OperationalError: unable to open database file

Here's the app.py:

from embedchain import Pipeline as App

# load embedding model configuration from config.yaml file
app = App.from_config(yaml_path="config.yaml") 

config.yaml :  

llm:
  provider: huggingface
  config:
    model: 'google/flan-t5-xxl'
    temperature: 0.5
    max_tokens: 1000
    top_p: 0.5
    stream: false

embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'

vectordb:
  provider: chroma
  config:
    collection_name: 'my-collection'
    dir: db
    allow_reset: true    

Here's the app.py

**Comment by sidmohanty11** [comment]
Hey @Yusufibin what is the version of Embedchain that you're using? This issue was recently fixed, if you're using an older version can you try the latest one? Please let me know if you have this issue. Thanks!

**Comment by denisj** [comment]
I'm using embedchain v0.1.17 within docker compose environment. I'm experiencing the same issue.
```
celery_worker_1  | Traceback (most recent call last):
celery_worker_1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
celery_worker_1  |     R = retval = fun(*args, **kwargs)
celery_worker_1  |                  ^^^^^^^^^^^^^^^^^^^^
celery_worker_1  |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
celery_worker_1  |     return self.run(*args, **kwargs)
celery_worker_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_1  |   File "/app/project/tasks.py", line 26, in add_article
celery_worker_1  |     app = create_embedchain_app(collection_name)
celery_worker_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_1  |   File "/app/embedchain_app/__init__.py", line 53, in create_embedchain_app
celery_worker_1  |     llm = OpenAILlm(
celery_worker_1  |           ^^^^^^^^^^
celery_worker_1  |   File "/usr/local/lib/python3.11/site-packages/embedchain/llm/openai.py", line 14, in __init__
celery_worker_1  |     super().__init__(config=config)
celery_worker_1  |   File "/usr/local/lib/python3.11/site-packages/embedchain/llm/base.py", line 27, in __init__
celery_worker_1  |     self.memory = ECChatMemory()
celery_worker_1  |                   ^^^^^^^^^^^^^^
celery_worker_1  |   File "/usr/local/lib/python3.11/site-packages/embedchain/memory/base.py", line 26, in __init__
celery_worker_1  |     with sqlite3.connect(SQLITE_PATH) as self.connection:
celery_worker_1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_1  | sqlite3.OperationalError: unable to open database file
```

**Comment by deshraj** [comment]
@Yusufibin looks like you are not using the latest version of Embedchain package. Can you please update and try again?
