### ISSUE TITLE
Non-feature request - Modularize the application

### ISSUE THREAD

**Issue by aaishikdutta** [embedchain/embedchain#95]
The Embedchain class has a lot of methods and it would add value in terms of code readability to abstract it a little bit. There are many open issues about integrating multiple llms, vector dbs or embedding. While I see a level of abstraction in the vector db folder and that can be leveraged for further integration options, I believe we should do something similar for the methods where we use the embedding models and the llm model. I have raised a PR for this #92  which attends to abstracting the data formats for loaders and chunkers . @taranjeet @cachho please let me know if this is something we can add, so we can have some further discussions on how to structure it for the more critical pieces like the  embedding models and chat completions.

**Comment by taranjeet** [comment]
Hey @aaishikdutta , I am getting back to this issue in some time.

**Comment by cachho** [comment]
Since you tagged me, I think we have should merge #70 first, and then get back to this idea. Thanks for the PR.

**Comment by aaidutta** [comment]
@cachho sounds good 💯

**Comment by taranjeet** [comment]
We are already revamping the framework, so closing this issue for now.
