### ISSUE TITLE
hello world error:TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by yangboyd** [embedchain/embedchain#959]
### 🐛 Describe the bug

You can find this env variable on your [OpenAI dashboard](https://platform.openai.com/account/api-keys).

+ Code

+ Markdown

Code

import os
from embedchain import Pipeline as App

os.environ["OPENAI_API_KEY"] = "sk-xxx"
os.environ["OPENAI_API_BASE"] = "http://xxx"
import os
from embedchain import Pipeline as App
​
os.environ["OPENAI_API_KEY"] = "sk-xxx"
os.environ["OPENAI_API_BASE"] = "http://xxxxx"
0秒
TypeError: 'type' object is not subscriptable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 2
      1 import os
----> 2 from embedchain import Pipeline as App
      4 os.environ["OPENAI_API_KEY"] = "sk-xxx"
      5 os.environ["OPENAI_API_BASE"] = "[http://xxx:3000]"

File /mnt/workspace/Embedchain/embedchain/__init__.py:5
      1 import importlib.metadata
      3 __version__ = importlib.metadata.version(__package__ or __name__)
----> 5 from embedchain.apps.app import App  # noqa: F401
      6 from embedchain.client import Client  # noqa: F401
      7 from embedchain.pipeline import Pipeline  # noqa: F401

File /mnt/workspace/Embedchain/embedchain/apps/app.py:6
      3 import yaml
      5 from embedchain.client import Client
----> 6 from embedchain.config import (AppConfig, BaseEmbedderConfig, BaseLlmConfig,
      7                                ChunkerConfig)
      8 from embedchain.config.vectordb.base import BaseVectorDbConfig
      9 from embedchain.embedchain import EmbedChain

File /mnt/workspace/Embedchain/embedchain/config/__init__.py:4
      1 # flake8: noqa: F401
      3 from .add_config import AddConfig, ChunkerConfig
----> 4 from .apps.app_config import AppConfig
      5 from .base_config import BaseConfig
      6 from .embedder.base import BaseEmbedderConfig

File /mnt/workspace/Embedchain/embedchain/config/apps/app_config.py:5
      1 from typing import Optional
      3 from embedchain.helper.json_serializable import register_deserializable
----> 5 from .base_app_config import BaseAppConfig
      8 @register_deserializable
      9 class AppConfig(BaseAppConfig):
     10     """
     11     Config to initialize an embedchain custom `App` instance, with extra config options.
     12     """

File /mnt/workspace/Embedchain/embedchain/config/apps/base_app_config.py:6
      4 from embedchain.config.base_config import BaseConfig
      5 from embedchain.helper.json_serializable import JSONSerializable
----> 6 from embedchain.vectordb.base import BaseVectorDB
      9 class BaseAppConfig(BaseConfig, JSONSerializable):
     10     """
     11     Parent config to initialize an instance of `App`.
     12     """

File /mnt/workspace/Embedchain/embedchain/vectordb/base.py:2
      1 from embedchain.config.vectordb.base import BaseVectorDbConfig
----> 2 from embedchain.embedder.base import BaseEmbedder
      3 from embedchain.helper.json_serializable import JSONSerializable
      6 class BaseVectorDB(JSONSerializable):

File /mnt/workspace/Embedchain/embedchain/embedder/base.py:14
     10     use_pysqlite3()
     11     from chromadb.api.types import Documents, Embeddings
---> 14 class BaseEmbedder:
     15     """
     16     Class that manages everything regarding embeddings. Including embedding function, loaders and chunkers.
     17 
     18     Embedding functions and vector dimensions are set based on the child class you choose.
     19     To manually overwrite you can use this classes `set_...` methods.
     20     """
     22     def __init__(self, config: Optional[BaseEmbedderConfig] = None):

File /mnt/workspace/Embedchain/embedchain/embedder/base.py:35, in BaseEmbedder()
     32         self.config = config
     33     self.vector_dimension: int
---> 35 def set_embedding_fn(self, embedding_fn: Callable[[list[str]], list[str]]):
     36     """
     37     Set or overwrite the embedding function to be used by the database to store and retrieve documents.
     38 
   (...)
     41     :raises ValueError: Embedding function is not callable.
     42     """
     43     if not hasattr(embedding_fn, "__call__"):

TypeError: 'type' object is not subscriptable

**Comment by deshraj** [comment]
Thanks for reporting the issue @yangboyd. Can you please tell what version of Embedchain you are using? 

You can find the version using the following command:

```python
import embedchain
embedchain.__version__
```

**Comment by yangboyd** [comment]
+ Code

+ Markdown

Code






import sys
print(sys.version)

import embedchain
embedchain.__version__
import sys
print(sys.version)
​
import embedchain
embedchain.__version__
0秒
3.8.16 (default, Jun 12 2023, 18:09:05) 
[GCC 11.2.0]
TypeError: 'type' object is not subscriptable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 4
      1 import sys
      2 print(sys.version)
----> 4 import embedchain
      5 embedchain.__version__

File /mnt/workspace/Embedchain/embedchain/__init__.py:5
      1 import importlib.metadata
      3 __version__ = importlib.metadata.version(__package__ or __name__)
----> 5 from embedchain.apps.app import App  # noqa: F401
      6 from embedchain.client import Client  # noqa: F401
      7 from embedchain.pipeline import Pipeline  # noqa: F401

File /mnt/workspace/Embedchain/embedchain/apps/app.py:6
      3 import yaml
      5 from embedchain.client import Client
----> 6 from embedchain.config import (AppConfig, BaseEmbedderConfig, BaseLlmConfig,
      7                                ChunkerConfig)
      8 from embedchain.config.vectordb.base import BaseVectorDbConfig
      9 from embedchain.embedchain import EmbedChain

File /mnt/workspace/Embedchain/embedchain/config/__init__.py:4
      1 # flake8: noqa: F401
      3 from .add_config import AddConfig, ChunkerConfig
----> 4 from .apps.app_config import AppConfig
      5 from .base_config import BaseConfig
      6 from .embedder.base import BaseEmbedderConfig

File /mnt/workspace/Embedchain/embedchain/config/apps/app_config.py:5
      1 from typing import Optional
      3 from embedchain.helper.json_serializable import register_deserializable
----> 5 from .base_app_config import BaseAppConfig
      8 @register_deserializable
      9 class AppConfig(BaseAppConfig):
     10     """
     11     Config to initialize an embedchain custom `App` instance, with extra config options.
     12     """

File /mnt/workspace/Embedchain/embedchain/config/apps/base_app_config.py:6
      4 from embedchain.config.base_config import BaseConfig
      5 from embedchain.helper.json_serializable import JSONSerializable
----> 6 from embedchain.vectordb.base import BaseVectorDB
      9 class BaseAppConfig(BaseConfig, JSONSerializable):
     10     """
     11     Parent config to initialize an instance of `App`.
     12     """

File /mnt/workspace/Embedchain/embedchain/vectordb/base.py:2
      1 from embedchain.config.vectordb.base import BaseVectorDbConfig
----> 2 from embedchain.embedder.base import BaseEmbedder
      3 from embedchain.helper.json_serializable import JSONSerializable
      6 class BaseVectorDB(JSONSerializable):

File /mnt/workspace/Embedchain/embedchain/embedder/base.py:14
     10     use_pysqlite3()
     11     from chromadb.api.types import Documents, Embeddings
---> 14 class BaseEmbedder:
     15     """
     16     Class that manages everything regarding embeddings. Including embedding function, loaders and chunkers.
     17 
     18     Embedding functions and vector dimensions are set based on the child class you choose.
     19     To manually overwrite you can use this classes `set_...` methods.
     20     """
     22     def __init__(self, config: Optional[BaseEmbedderConfig] = None):

File /mnt/workspace/Embedchain/embedchain/embedder/base.py:35, in BaseEmbedder()
     32         self.config = config
     33     self.vector_dimension: int
---> 35 def set_embedding_fn(self, embedding_fn: Callable[[list[str]], list[str]]):
     36     """
     37     Set or overwrite the embedding function to be used by the database to store and retrieve documents.
     38 
   (...)
     41     :raises ValueError: Embedding function is not callable.
     42     """
     43     if not hasattr(embedding_fn, "__call__"):

TypeError: 'type' object is not subscriptable

**Comment by deshraj** [comment]
Looks like you are using older version of python which is not supported by Embedchain. Please upgrade to 3.9 or above. Thanks!
