### ISSUE TITLE
Consider using Pinecone instead of ChromaDB for improved functionality and installation experience

### ISSUE THREAD

**Issue by Madhav-MKNC** [embedchain/embedchain#96]
By using Pinecone, you may be able to overcome the installation errors associated with ChromaDB and benefit from a more efficient and reliable solution. Pinecone provides a user-friendly Python SDK and comprehensive documentation, making it easier for developers to integrate and work with the database.

**Comment by taranjeet** [comment]
Hey, we are using Chroma because it does not require any signup.
However we do plan to support Pinecone, tracking pinecone support here: https://github.com/embedchain/embedchain/issues/39

Closing this issue.
