### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by amjadraza** [embedchain/embedchain#98]
The Package was working fine with me few days ago, However after deleting DB and creating it again, I am having the below issue. 

No matter what prompt, I tried it throws same error. 

File "/mnt/c/Users/User/Documents/python_projects/embedchain-streamlit-app/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/mnt/c/Users/User/Documents/python_projects/embedchain-streamlit-app/demo_app/main.py", line 116, in <module>
    assistant_response = response_embedchain(user_input)
File "/mnt/c/Users/User/Documents/python_projects/embedchain-streamlit-app/demo_app/main.py", line 28, in response_embedchain
    response = naval_chat_bot.query(query)
File "/mnt/c/Users/User/Documents/python_projects/embedchain-streamlit-app/.venv/lib/python3.10/site-packages/embedchain/embedchain.py", line 224, in query
    context = self.retrieve_from_database(input_query)
File "/mnt/c/Users/User/Documents/python_projects/embedchain-streamlit-app/.venv/lib/python3.10/site-packages/embedchain/embedchain.py", line 185, in retrieve_from_database
    content = result_formatted[0][0].page_content

**Comment by xumeng** [comment]
I copy the code file and database files, and it report same error.

**Comment by cachho** [comment]
When you initialize the application, what does it say how many embeddings it found? Usually, this error indicates that there was no embedding found for your query. From my experience, this happens when the database got wiped for some reason (at this point I can't say why that happens). Maybe it could also be if there's nothing in your database that matches the query.

```
[INFO] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[INFO] NumExpr defaulting to 8 threads.
[INFO] Successfully imported ClickHouse Connect C data optimizations
[INFO] Using python library for writing JSON byte strings
[INFO] loaded in 1706 embeddings
[INFO] loaded in 1 collections
[INFO] collection with name embedchain_store already exists, returning existing collection
```

**Comment by amjadraza** [comment]
It takes some time to get the Embeddings ready. Probably, we should add some await message before we can send the request.

**Comment by cachho** [comment]
> It takes some time to get the Embeddings ready. Probably, we should add some await message before we can send the request.

I noticed that too, that it seems to be asyncronous. Maybe, if we return the values (#109) it forces python to wait? I don't know where the async part comes in (most likely Chroma), and async has advantages if you try to iterate over a large list.

Maybe synchronous should be the default and async optional. 

However, you can solve your problems by making one script that handles the database operations (.add) and one for querying (.query). If you want to go further, you can use the client server model that hopefully get's introduced with #117. That's how I do it in production, with Flask and Gunicorn and a Chroma Server in Docker.

**Comment by taranjeet** [comment]
THis issue has not been reported for the past few weeks. so closing this.
feel free to reopen it.
